// @generated by protoc-gen-es v2.9.0 with parameter "target=ts"
// @generated from file cosmos/circuit/module/v1/module.proto (package cosmos.circuit.module.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_cosmos_app_v1alpha1_module } from "../../../app/v1alpha1/module_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file cosmos/circuit/module/v1/module.proto.
 */
export const file_cosmos_circuit_module_v1_module: GenFile = /*@__PURE__*/
  fileDesc("CiVjb3Ntb3MvY2lyY3VpdC9tb2R1bGUvdjEvbW9kdWxlLnByb3RvEhhjb3Ntb3MuY2lyY3VpdC5tb2R1bGUudjEiOwoGTW9kdWxlEhEKCWF1dGhvcml0eRgBIAEoCToeusCW2gEYChZjb3Ntb3NzZGsuaW8veC9jaXJjdWl0Qq4BChxjb20uY29zbW9zLmNpcmN1aXQubW9kdWxlLnYxQgtNb2R1bGVQcm90b1ABogIDQ0NNqgIYQ29zbW9zLkNpcmN1aXQuTW9kdWxlLlYxygIYQ29zbW9zXENpcmN1aXRcTW9kdWxlXFYx4gIkQ29zbW9zXENpcmN1aXRcTW9kdWxlXFYxXEdQQk1ldGFkYXRh6gIbQ29zbW9zOjpDaXJjdWl0OjpNb2R1bGU6OlYxYgZwcm90bzM", [file_cosmos_app_v1alpha1_module]);

/**
 * Module is the config object of the circuit module.
 *
 * @generated from message cosmos.circuit.module.v1.Module
 */
export type Module = Message<"cosmos.circuit.module.v1.Module"> & {
  /**
   * authority defines the custom module authority. If not set, defaults to the
   * governance module.
   *
   * @generated from field: string authority = 1;
   */
  authority: string;
};

/**
 * Describes the message cosmos.circuit.module.v1.Module.
 * Use `create(ModuleSchema)` to create a new message.
 */
export const ModuleSchema: GenMessage<Module> = /*@__PURE__*/
  messageDesc(file_cosmos_circuit_module_v1_module, 0);

