// @generated by protoc-gen-es v2.9.0 with parameter "target=ts"
// @generated from file ibc/core/connection/v1/connection.proto (package ibc.core.connection.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_gogoproto_gogo } from "../../../../gogoproto/gogo_pb";
import type { MerklePrefix } from "../../commitment/v1/commitment_pb";
import { file_ibc_core_commitment_v1_commitment } from "../../commitment/v1/commitment_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file ibc/core/connection/v1/connection.proto.
 */
export const file_ibc_core_connection_v1_connection: GenFile = /*@__PURE__*/
  fileDesc("CidpYmMvY29yZS9jb25uZWN0aW9uL3YxL2Nvbm5lY3Rpb24ucHJvdG8SFmliYy5jb3JlLmNvbm5lY3Rpb24udjEi4QEKDUNvbm5lY3Rpb25FbmQSEQoJY2xpZW50X2lkGAEgASgJEjEKCHZlcnNpb25zGAIgAygLMh8uaWJjLmNvcmUuY29ubmVjdGlvbi52MS5WZXJzaW9uEiwKBXN0YXRlGAMgASgOMh0uaWJjLmNvcmUuY29ubmVjdGlvbi52MS5TdGF0ZRJACgxjb3VudGVycGFydHkYBCABKAsyJC5pYmMuY29yZS5jb25uZWN0aW9uLnYxLkNvdW50ZXJwYXJ0eUIEyN4fABIUCgxkZWxheV9wZXJpb2QYBSABKAQ6BIigHwAi9AEKFElkZW50aWZpZWRDb25uZWN0aW9uEgoKAmlkGAEgASgJEhEKCWNsaWVudF9pZBgCIAEoCRIxCgh2ZXJzaW9ucxgDIAMoCzIfLmliYy5jb3JlLmNvbm5lY3Rpb24udjEuVmVyc2lvbhIsCgVzdGF0ZRgEIAEoDjIdLmliYy5jb3JlLmNvbm5lY3Rpb24udjEuU3RhdGUSQAoMY291bnRlcnBhcnR5GAUgASgLMiQuaWJjLmNvcmUuY29ubmVjdGlvbi52MS5Db3VudGVycGFydHlCBMjeHwASFAoMZGVsYXlfcGVyaW9kGAYgASgEOgSIoB8AInoKDENvdW50ZXJwYXJ0eRIRCgljbGllbnRfaWQYASABKAkSFQoNY29ubmVjdGlvbl9pZBgCIAEoCRI6CgZwcmVmaXgYAyABKAsyJC5pYmMuY29yZS5jb21taXRtZW50LnYxLk1lcmtsZVByZWZpeEIEyN4fADoEiKAfACIcCgtDbGllbnRQYXRocxINCgVwYXRocxgBIAMoCSIzCg9Db25uZWN0aW9uUGF0aHMSEQoJY2xpZW50X2lkGAEgASgJEg0KBXBhdGhzGAIgAygJIjUKB1ZlcnNpb24SEgoKaWRlbnRpZmllchgBIAEoCRIQCghmZWF0dXJlcxgCIAMoCToEiKAfACItCgZQYXJhbXMSIwobbWF4X2V4cGVjdGVkX3RpbWVfcGVyX2Jsb2NrGAEgASgEKpkBCgVTdGF0ZRI2Ch9TVEFURV9VTklOSVRJQUxJWkVEX1VOU1BFQ0lGSUVEEAAaEYqdIA1VTklOSVRJQUxJWkVEEhgKClNUQVRFX0lOSVQQARoIip0gBElOSVQSHgoNU1RBVEVfVFJZT1BFThACGguKnSAHVFJZT1BFThIYCgpTVEFURV9PUEVOEAMaCIqdIARPUEVOGgSIox4AQucBChpjb20uaWJjLmNvcmUuY29ubmVjdGlvbi52MUIPQ29ubmVjdGlvblByb3RvUAFaPWdpdGh1Yi5jb20vY29zbW9zL2liYy1nby92MTAvbW9kdWxlcy9jb3JlLzAzLWNvbm5lY3Rpb24vdHlwZXOiAgNJQ0OqAhZJYmMuQ29yZS5Db25uZWN0aW9uLlYxygIWSWJjXENvcmVcQ29ubmVjdGlvblxWMeICIkliY1xDb3JlXENvbm5lY3Rpb25cVjFcR1BCTWV0YWRhdGHqAhlJYmM6OkNvcmU6OkNvbm5lY3Rpb246OlYxYgZwcm90bzM", [file_gogoproto_gogo, file_ibc_core_commitment_v1_commitment]);

/**
 * ConnectionEnd defines a stateful object on a chain connected to another
 * separate one.
 * NOTE: there must only be 2 defined ConnectionEnds to establish
 * a connection between two chains.
 *
 * @generated from message ibc.core.connection.v1.ConnectionEnd
 */
export type ConnectionEnd = Message<"ibc.core.connection.v1.ConnectionEnd"> & {
  /**
   * client associated with this connection.
   *
   * @generated from field: string client_id = 1;
   */
  clientId: string;

  /**
   * IBC version which can be utilised to determine encodings or protocols for
   * channels or packets utilising this connection.
   *
   * @generated from field: repeated ibc.core.connection.v1.Version versions = 2;
   */
  versions: Version[];

  /**
   * current state of the connection end.
   *
   * @generated from field: ibc.core.connection.v1.State state = 3;
   */
  state: State;

  /**
   * counterparty chain associated with this connection.
   *
   * @generated from field: ibc.core.connection.v1.Counterparty counterparty = 4;
   */
  counterparty?: Counterparty;

  /**
   * delay period that must pass before a consensus state can be used for
   * packet-verification NOTE: delay period logic is only implemented by some
   * clients.
   *
   * @generated from field: uint64 delay_period = 5;
   */
  delayPeriod: bigint;
};

/**
 * Describes the message ibc.core.connection.v1.ConnectionEnd.
 * Use `create(ConnectionEndSchema)` to create a new message.
 */
export const ConnectionEndSchema: GenMessage<ConnectionEnd> = /*@__PURE__*/
  messageDesc(file_ibc_core_connection_v1_connection, 0);

/**
 * IdentifiedConnection defines a connection with additional connection
 * identifier field.
 *
 * @generated from message ibc.core.connection.v1.IdentifiedConnection
 */
export type IdentifiedConnection = Message<"ibc.core.connection.v1.IdentifiedConnection"> & {
  /**
   * connection identifier.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * client associated with this connection.
   *
   * @generated from field: string client_id = 2;
   */
  clientId: string;

  /**
   * IBC version which can be utilised to determine encodings or protocols for
   * channels or packets utilising this connection
   *
   * @generated from field: repeated ibc.core.connection.v1.Version versions = 3;
   */
  versions: Version[];

  /**
   * current state of the connection end.
   *
   * @generated from field: ibc.core.connection.v1.State state = 4;
   */
  state: State;

  /**
   * counterparty chain associated with this connection.
   *
   * @generated from field: ibc.core.connection.v1.Counterparty counterparty = 5;
   */
  counterparty?: Counterparty;

  /**
   * delay period associated with this connection.
   *
   * @generated from field: uint64 delay_period = 6;
   */
  delayPeriod: bigint;
};

/**
 * Describes the message ibc.core.connection.v1.IdentifiedConnection.
 * Use `create(IdentifiedConnectionSchema)` to create a new message.
 */
export const IdentifiedConnectionSchema: GenMessage<IdentifiedConnection> = /*@__PURE__*/
  messageDesc(file_ibc_core_connection_v1_connection, 1);

/**
 * Counterparty defines the counterparty chain associated with a connection end.
 *
 * @generated from message ibc.core.connection.v1.Counterparty
 */
export type Counterparty = Message<"ibc.core.connection.v1.Counterparty"> & {
  /**
   * identifies the client on the counterparty chain associated with a given
   * connection.
   *
   * @generated from field: string client_id = 1;
   */
  clientId: string;

  /**
   * identifies the connection end on the counterparty chain associated with a
   * given connection.
   *
   * @generated from field: string connection_id = 2;
   */
  connectionId: string;

  /**
   * commitment merkle prefix of the counterparty chain.
   *
   * @generated from field: ibc.core.commitment.v1.MerklePrefix prefix = 3;
   */
  prefix?: MerklePrefix;
};

/**
 * Describes the message ibc.core.connection.v1.Counterparty.
 * Use `create(CounterpartySchema)` to create a new message.
 */
export const CounterpartySchema: GenMessage<Counterparty> = /*@__PURE__*/
  messageDesc(file_ibc_core_connection_v1_connection, 2);

/**
 * ClientPaths define all the connection paths for a client state.
 *
 * @generated from message ibc.core.connection.v1.ClientPaths
 */
export type ClientPaths = Message<"ibc.core.connection.v1.ClientPaths"> & {
  /**
   * list of connection paths
   *
   * @generated from field: repeated string paths = 1;
   */
  paths: string[];
};

/**
 * Describes the message ibc.core.connection.v1.ClientPaths.
 * Use `create(ClientPathsSchema)` to create a new message.
 */
export const ClientPathsSchema: GenMessage<ClientPaths> = /*@__PURE__*/
  messageDesc(file_ibc_core_connection_v1_connection, 3);

/**
 * ConnectionPaths define all the connection paths for a given client state.
 *
 * @generated from message ibc.core.connection.v1.ConnectionPaths
 */
export type ConnectionPaths = Message<"ibc.core.connection.v1.ConnectionPaths"> & {
  /**
   * client state unique identifier
   *
   * @generated from field: string client_id = 1;
   */
  clientId: string;

  /**
   * list of connection paths
   *
   * @generated from field: repeated string paths = 2;
   */
  paths: string[];
};

/**
 * Describes the message ibc.core.connection.v1.ConnectionPaths.
 * Use `create(ConnectionPathsSchema)` to create a new message.
 */
export const ConnectionPathsSchema: GenMessage<ConnectionPaths> = /*@__PURE__*/
  messageDesc(file_ibc_core_connection_v1_connection, 4);

/**
 * Version defines the versioning scheme used to negotiate the IBC version in
 * the connection handshake.
 *
 * @generated from message ibc.core.connection.v1.Version
 */
export type Version = Message<"ibc.core.connection.v1.Version"> & {
  /**
   * unique version identifier
   *
   * @generated from field: string identifier = 1;
   */
  identifier: string;

  /**
   * list of features compatible with the specified identifier
   *
   * @generated from field: repeated string features = 2;
   */
  features: string[];
};

/**
 * Describes the message ibc.core.connection.v1.Version.
 * Use `create(VersionSchema)` to create a new message.
 */
export const VersionSchema: GenMessage<Version> = /*@__PURE__*/
  messageDesc(file_ibc_core_connection_v1_connection, 5);

/**
 * Params defines the set of Connection parameters.
 *
 * @generated from message ibc.core.connection.v1.Params
 */
export type Params = Message<"ibc.core.connection.v1.Params"> & {
  /**
   * maximum expected time per block (in nanoseconds), used to enforce block
   * delay. This parameter should reflect the largest amount of time that the
   * chain might reasonably take to produce the next block under normal
   * operating conditions. A safe choice is 3-5x the expected time per block.
   *
   * @generated from field: uint64 max_expected_time_per_block = 1;
   */
  maxExpectedTimePerBlock: bigint;
};

/**
 * Describes the message ibc.core.connection.v1.Params.
 * Use `create(ParamsSchema)` to create a new message.
 */
export const ParamsSchema: GenMessage<Params> = /*@__PURE__*/
  messageDesc(file_ibc_core_connection_v1_connection, 6);

/**
 * State defines if a connection is in one of the following states:
 * INIT, TRYOPEN, OPEN or UNINITIALIZED.
 *
 * @generated from enum ibc.core.connection.v1.State
 */
export enum State {
  /**
   * Default State
   *
   * @generated from enum value: STATE_UNINITIALIZED_UNSPECIFIED = 0;
   */
  UNINITIALIZED_UNSPECIFIED = 0,

  /**
   * A connection end has just started the opening handshake.
   *
   * @generated from enum value: STATE_INIT = 1;
   */
  INIT = 1,

  /**
   * A connection end has acknowledged the handshake step on the counterparty
   * chain.
   *
   * @generated from enum value: STATE_TRYOPEN = 2;
   */
  TRYOPEN = 2,

  /**
   * A connection end has completed the handshake.
   *
   * @generated from enum value: STATE_OPEN = 3;
   */
  OPEN = 3,
}

/**
 * Describes the enum ibc.core.connection.v1.State.
 */
export const StateSchema: GenEnum<State> = /*@__PURE__*/
  enumDesc(file_ibc_core_connection_v1_connection, 0);

