// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file dysonprotocol/nameservice/v1/genesis.proto (package dysonprotocol.nameservice.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64 } from "@bufbuild/protobuf";
import { Params } from "./params_pb.js";
import { BidRecord, Commitment } from "./nameservice_pb.js";

/**
 * GenesisState defines the nameservice module's genesis state.
 *
 * @generated from message dysonprotocol.nameservice.v1.GenesisState
 */
export class GenesisState extends Message<GenesisState> {
  /**
   * params defines all the parameters of the module.
   *
   * @generated from field: dysonprotocol.nameservice.v1.Params params = 1;
   */
  params?: Params;

  /**
   * @generated from field: repeated dysonprotocol.nameservice.v1.Commitment commitments = 3;
   */
  commitments: Commitment[] = [];

  /**
   * Bid ledger authoritative state; secondary indexes are rebuilt at import
   *
   * @generated from field: uint64 bid_seq = 4;
   */
  bidSeq = protoInt64.zero;

  /**
   * @generated from field: repeated dysonprotocol.nameservice.v1.BidRecord bids = 5;
   */
  bids: BidRecord[] = [];

  constructor(data?: PartialMessage<GenesisState>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dysonprotocol.nameservice.v1.GenesisState";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "params", kind: "message", T: Params },
    { no: 3, name: "commitments", kind: "message", T: Commitment, repeated: true },
    { no: 4, name: "bid_seq", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 5, name: "bids", kind: "message", T: BidRecord, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GenesisState {
    return new GenesisState().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GenesisState {
    return new GenesisState().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GenesisState {
    return new GenesisState().fromJsonString(jsonString, options);
  }

  static equals(a: GenesisState | PlainMessage<GenesisState> | undefined, b: GenesisState | PlainMessage<GenesisState> | undefined): boolean {
    return proto3.util.equals(GenesisState, a, b);
  }
}

