// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts"
// @generated from file dysonprotocol/nameservice/v1/query.proto (package dysonprotocol.nameservice.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { QueryBidsByBidderRequest, QueryBidsByBidderResponse, QueryBidsForNFTRequest, QueryBidsForNFTResponse, QueryComputeHashRequest, QueryComputeHashResponse, QueryDenomByNameRequest, QueryDenomByNameResponse, QueryNamesByDestinationRequest, QueryNamesByDestinationResponse, QueryNFTClassesByNameRequest, QueryNFTClassesByNameResponse, QueryParamsRequest, QueryParamsResponse, QueryResolveNameRequest, QueryResolveNameResponse } from "./query_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * Query defines the gRPC querier service.
 *
 * @generated from service dysonprotocol.nameservice.v1.Query
 */
export const Query = {
  typeName: "dysonprotocol.nameservice.v1.Query",
  methods: {
    /**
     * ComputeHash computes the hash for a name, salt, and committer address
     *
     * @generated from rpc dysonprotocol.nameservice.v1.Query.ComputeHash
     */
    computeHash: {
      name: "ComputeHash",
      I: QueryComputeHashRequest,
      O: QueryComputeHashResponse,
      kind: MethodKind.Unary,
    },
    /**
     * ResolveName resolves a name to address or returns the address if already
     * valid
     *
     * @generated from rpc dysonprotocol.nameservice.v1.Query.ResolveName
     */
    resolveName: {
      name: "ResolveName",
      I: QueryResolveNameRequest,
      O: QueryResolveNameResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Params queries the nameservice module parameters
     *
     * @generated from rpc dysonprotocol.nameservice.v1.Query.Params
     */
    params: {
      name: "Params",
      I: QueryParamsRequest,
      O: QueryParamsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * QueryNamesByDestination queries all names pointing to a destination address
     *
     * @generated from rpc dysonprotocol.nameservice.v1.Query.QueryNamesByDestination
     */
    queryNamesByDestination: {
      name: "QueryNamesByDestination",
      I: QueryNamesByDestinationRequest,
      O: QueryNamesByDestinationResponse,
      kind: MethodKind.Unary,
    },
    /**
     * QueryNFTClassesByName lists NFT class IDs under a given root name
     *
     * @generated from rpc dysonprotocol.nameservice.v1.Query.QueryNFTClassesByName
     */
    queryNFTClassesByName: {
      name: "QueryNFTClassesByName",
      I: QueryNFTClassesByNameRequest,
      O: QueryNFTClassesByNameResponse,
      kind: MethodKind.Unary,
    },
    /**
     * QueryDenomByName lists denoms under a given root name along with details
     *
     * @generated from rpc dysonprotocol.nameservice.v1.Query.QueryDenomByName
     */
    queryDenomByName: {
      name: "QueryDenomByName",
      I: QueryDenomByNameRequest,
      O: QueryDenomByNameResponse,
      kind: MethodKind.Unary,
    },
    /**
     * QueryBidsByBidder lists bids placed by a bidder across NFTs
     *
     * @generated from rpc dysonprotocol.nameservice.v1.Query.QueryBidsByBidder
     */
    queryBidsByBidder: {
      name: "QueryBidsByBidder",
      I: QueryBidsByBidderRequest,
      O: QueryBidsByBidderResponse,
      kind: MethodKind.Unary,
    },
    /**
     * QueryBidsForNFT lists all bids for a given NFT
     *
     * @generated from rpc dysonprotocol.nameservice.v1.Query.QueryBidsForNFT
     */
    queryBidsForNFT: {
      name: "QueryBidsForNFT",
      I: QueryBidsForNFTRequest,
      O: QueryBidsForNFTResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

