// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file dysonprotocol/nameservice/v1/query.proto (package dysonprotocol.nameservice.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import { Params } from "./params_pb.js";
import { PageRequest, PageResponse } from "../../../cosmos/base/query/v1beta1/pagination_pb.js";
import { BidRecord, BidStatus, BidWithNFTStatus } from "./nameservice_pb.js";

/**
 * QueryComputeHashRequest is a request to compute the hash for a name and salt
 *
 * @generated from message dysonprotocol.nameservice.v1.QueryComputeHashRequest
 */
export class QueryComputeHashRequest extends Message<QueryComputeHashRequest> {
  /**
   * name is the name to compute the hash for
   *
   * @generated from field: string name = 1;
   */
  name = "";

  /**
   * salt is the salt to use for the hash computation
   *
   * @generated from field: string salt = 2;
   */
  salt = "";

  /**
   * committer is the committer address
   *
   * @generated from field: string committer = 3;
   */
  committer = "";

  constructor(data?: PartialMessage<QueryComputeHashRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dysonprotocol.nameservice.v1.QueryComputeHashRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "salt", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "committer", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryComputeHashRequest {
    return new QueryComputeHashRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryComputeHashRequest {
    return new QueryComputeHashRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryComputeHashRequest {
    return new QueryComputeHashRequest().fromJsonString(jsonString, options);
  }

  static equals(a: QueryComputeHashRequest | PlainMessage<QueryComputeHashRequest> | undefined, b: QueryComputeHashRequest | PlainMessage<QueryComputeHashRequest> | undefined): boolean {
    return proto3.util.equals(QueryComputeHashRequest, a, b);
  }
}

/**
 * ComputeHashResponse contains the computed hash as a hex string
 *
 * @generated from message dysonprotocol.nameservice.v1.QueryComputeHashResponse
 */
export class QueryComputeHashResponse extends Message<QueryComputeHashResponse> {
  /**
   * hex_hash is the computed hash as a hex string
   *
   * @generated from field: string hex_hash = 1;
   */
  hexHash = "";

  constructor(data?: PartialMessage<QueryComputeHashResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dysonprotocol.nameservice.v1.QueryComputeHashResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "hex_hash", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryComputeHashResponse {
    return new QueryComputeHashResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryComputeHashResponse {
    return new QueryComputeHashResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryComputeHashResponse {
    return new QueryComputeHashResponse().fromJsonString(jsonString, options);
  }

  static equals(a: QueryComputeHashResponse | PlainMessage<QueryComputeHashResponse> | undefined, b: QueryComputeHashResponse | PlainMessage<QueryComputeHashResponse> | undefined): boolean {
    return proto3.util.equals(QueryComputeHashResponse, a, b);
  }
}

/**
 * QueryResolveNameRequest is request type for the Query/ResolveName RPC method.
 *
 * @generated from message dysonprotocol.nameservice.v1.QueryResolveNameRequest
 */
export class QueryResolveNameRequest extends Message<QueryResolveNameRequest> {
  /**
   * name_or_address is either a nameservice name or a valid address
   *
   * @generated from field: string name_or_address = 1;
   */
  nameOrAddress = "";

  constructor(data?: PartialMessage<QueryResolveNameRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dysonprotocol.nameservice.v1.QueryResolveNameRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "name_or_address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryResolveNameRequest {
    return new QueryResolveNameRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryResolveNameRequest {
    return new QueryResolveNameRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryResolveNameRequest {
    return new QueryResolveNameRequest().fromJsonString(jsonString, options);
  }

  static equals(a: QueryResolveNameRequest | PlainMessage<QueryResolveNameRequest> | undefined, b: QueryResolveNameRequest | PlainMessage<QueryResolveNameRequest> | undefined): boolean {
    return proto3.util.equals(QueryResolveNameRequest, a, b);
  }
}

/**
 * QueryResolveNameResponse is response type for the Query/ResolveName RPC
 * method.
 *
 * @generated from message dysonprotocol.nameservice.v1.QueryResolveNameResponse
 */
export class QueryResolveNameResponse extends Message<QueryResolveNameResponse> {
  /**
   * address is the resolved address
   *
   * @generated from field: string address = 1;
   */
  address = "";

  constructor(data?: PartialMessage<QueryResolveNameResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dysonprotocol.nameservice.v1.QueryResolveNameResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryResolveNameResponse {
    return new QueryResolveNameResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryResolveNameResponse {
    return new QueryResolveNameResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryResolveNameResponse {
    return new QueryResolveNameResponse().fromJsonString(jsonString, options);
  }

  static equals(a: QueryResolveNameResponse | PlainMessage<QueryResolveNameResponse> | undefined, b: QueryResolveNameResponse | PlainMessage<QueryResolveNameResponse> | undefined): boolean {
    return proto3.util.equals(QueryResolveNameResponse, a, b);
  }
}

/**
 * QueryParamsRequest is request type for the Query/Params RPC method.
 *
 * @generated from message dysonprotocol.nameservice.v1.QueryParamsRequest
 */
export class QueryParamsRequest extends Message<QueryParamsRequest> {
  constructor(data?: PartialMessage<QueryParamsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dysonprotocol.nameservice.v1.QueryParamsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryParamsRequest {
    return new QueryParamsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryParamsRequest {
    return new QueryParamsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryParamsRequest {
    return new QueryParamsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: QueryParamsRequest | PlainMessage<QueryParamsRequest> | undefined, b: QueryParamsRequest | PlainMessage<QueryParamsRequest> | undefined): boolean {
    return proto3.util.equals(QueryParamsRequest, a, b);
  }
}

/**
 * QueryParamsResponse is response type for the Query/Params RPC method.
 *
 * @generated from message dysonprotocol.nameservice.v1.QueryParamsResponse
 */
export class QueryParamsResponse extends Message<QueryParamsResponse> {
  /**
   * params holds all the parameters of this module.
   *
   * @generated from field: dysonprotocol.nameservice.v1.Params params = 1;
   */
  params?: Params;

  constructor(data?: PartialMessage<QueryParamsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dysonprotocol.nameservice.v1.QueryParamsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "params", kind: "message", T: Params },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryParamsResponse {
    return new QueryParamsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryParamsResponse {
    return new QueryParamsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryParamsResponse {
    return new QueryParamsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: QueryParamsResponse | PlainMessage<QueryParamsResponse> | undefined, b: QueryParamsResponse | PlainMessage<QueryParamsResponse> | undefined): boolean {
    return proto3.util.equals(QueryParamsResponse, a, b);
  }
}

/**
 * QueryNamesByDestinationRequest is request type for the
 * to list names by destination address or name
 *
 * @generated from message dysonprotocol.nameservice.v1.QueryNamesByDestinationRequest
 */
export class QueryNamesByDestinationRequest extends Message<QueryNamesByDestinationRequest> {
  /**
   * destination is the name or address to find names for
   *
   * @generated from field: string destination = 1;
   */
  destination = "";

  /**
   * pagination defines an optional pagination for the request.
   *
   * @generated from field: cosmos.base.query.v1beta1.PageRequest pagination = 2;
   */
  pagination?: PageRequest;

  constructor(data?: PartialMessage<QueryNamesByDestinationRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dysonprotocol.nameservice.v1.QueryNamesByDestinationRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "destination", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "pagination", kind: "message", T: PageRequest },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryNamesByDestinationRequest {
    return new QueryNamesByDestinationRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryNamesByDestinationRequest {
    return new QueryNamesByDestinationRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryNamesByDestinationRequest {
    return new QueryNamesByDestinationRequest().fromJsonString(jsonString, options);
  }

  static equals(a: QueryNamesByDestinationRequest | PlainMessage<QueryNamesByDestinationRequest> | undefined, b: QueryNamesByDestinationRequest | PlainMessage<QueryNamesByDestinationRequest> | undefined): boolean {
    return proto3.util.equals(QueryNamesByDestinationRequest, a, b);
  }
}

/**
 * @generated from message dysonprotocol.nameservice.v1.QueryNamesByDestinationResponse
 */
export class QueryNamesByDestinationResponse extends Message<QueryNamesByDestinationResponse> {
  /**
   * names is the list of name strings pointing to the destination address
   *
   * @generated from field: repeated string names = 1;
   */
  names: string[] = [];

  /**
   * pagination defines the pagination in the response.
   *
   * @generated from field: cosmos.base.query.v1beta1.PageResponse pagination = 2;
   */
  pagination?: PageResponse;

  constructor(data?: PartialMessage<QueryNamesByDestinationResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dysonprotocol.nameservice.v1.QueryNamesByDestinationResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "names", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 2, name: "pagination", kind: "message", T: PageResponse },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryNamesByDestinationResponse {
    return new QueryNamesByDestinationResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryNamesByDestinationResponse {
    return new QueryNamesByDestinationResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryNamesByDestinationResponse {
    return new QueryNamesByDestinationResponse().fromJsonString(jsonString, options);
  }

  static equals(a: QueryNamesByDestinationResponse | PlainMessage<QueryNamesByDestinationResponse> | undefined, b: QueryNamesByDestinationResponse | PlainMessage<QueryNamesByDestinationResponse> | undefined): boolean {
    return proto3.util.equals(QueryNamesByDestinationResponse, a, b);
  }
}

/**
 * QueryNFTClassesByNameRequest is request type for the
 * Query/QueryNFTClassesByName RPC method.
 *
 * @generated from message dysonprotocol.nameservice.v1.QueryNFTClassesByNameRequest
 */
export class QueryNFTClassesByNameRequest extends Message<QueryNFTClassesByNameRequest> {
  /**
   * name is the root name to list classes for
   *
   * @generated from field: string name = 1;
   */
  name = "";

  /**
   * subclass_prefix optionally filters to a sub-path under the name (e.g.
   * "/foo") If empty, all classes under the root including the base class are
   * returned
   *
   * @generated from field: string subclass_prefix = 3;
   */
  subclassPrefix = "";

  /**
   * pagination defines an optional pagination for the request.
   *
   * @generated from field: cosmos.base.query.v1beta1.PageRequest pagination = 2;
   */
  pagination?: PageRequest;

  constructor(data?: PartialMessage<QueryNFTClassesByNameRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dysonprotocol.nameservice.v1.QueryNFTClassesByNameRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "subclass_prefix", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "pagination", kind: "message", T: PageRequest },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryNFTClassesByNameRequest {
    return new QueryNFTClassesByNameRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryNFTClassesByNameRequest {
    return new QueryNFTClassesByNameRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryNFTClassesByNameRequest {
    return new QueryNFTClassesByNameRequest().fromJsonString(jsonString, options);
  }

  static equals(a: QueryNFTClassesByNameRequest | PlainMessage<QueryNFTClassesByNameRequest> | undefined, b: QueryNFTClassesByNameRequest | PlainMessage<QueryNFTClassesByNameRequest> | undefined): boolean {
    return proto3.util.equals(QueryNFTClassesByNameRequest, a, b);
  }
}

/**
 * QueryNFTClassesByNameResponse is response type for the
 * Query/QueryNFTClassesByName RPC method.
 *
 * @generated from message dysonprotocol.nameservice.v1.QueryNFTClassesByNameResponse
 */
export class QueryNFTClassesByNameResponse extends Message<QueryNFTClassesByNameResponse> {
  /**
   * class_ids is the list of NFT class IDs under the provided root name
   *
   * @generated from field: repeated string class_ids = 1;
   */
  classIds: string[] = [];

  /**
   * pagination defines the pagination in the response.
   *
   * @generated from field: cosmos.base.query.v1beta1.PageResponse pagination = 2;
   */
  pagination?: PageResponse;

  constructor(data?: PartialMessage<QueryNFTClassesByNameResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dysonprotocol.nameservice.v1.QueryNFTClassesByNameResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "class_ids", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 2, name: "pagination", kind: "message", T: PageResponse },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryNFTClassesByNameResponse {
    return new QueryNFTClassesByNameResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryNFTClassesByNameResponse {
    return new QueryNFTClassesByNameResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryNFTClassesByNameResponse {
    return new QueryNFTClassesByNameResponse().fromJsonString(jsonString, options);
  }

  static equals(a: QueryNFTClassesByNameResponse | PlainMessage<QueryNFTClassesByNameResponse> | undefined, b: QueryNFTClassesByNameResponse | PlainMessage<QueryNFTClassesByNameResponse> | undefined): boolean {
    return proto3.util.equals(QueryNFTClassesByNameResponse, a, b);
  }
}

/**
 * DenomDetails provides basic information about a custom denom
 *
 * @generated from message dysonprotocol.nameservice.v1.DenomDetails
 */
export class DenomDetails extends Message<DenomDetails> {
  /**
   * denom is the full denom string (e.g. "foo.dys/bar:baz")
   *
   * @generated from field: string denom = 1;
   */
  denom = "";

  constructor(data?: PartialMessage<DenomDetails>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dysonprotocol.nameservice.v1.DenomDetails";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "denom", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DenomDetails {
    return new DenomDetails().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DenomDetails {
    return new DenomDetails().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DenomDetails {
    return new DenomDetails().fromJsonString(jsonString, options);
  }

  static equals(a: DenomDetails | PlainMessage<DenomDetails> | undefined, b: DenomDetails | PlainMessage<DenomDetails> | undefined): boolean {
    return proto3.util.equals(DenomDetails, a, b);
  }
}

/**
 * QueryDenomByNameRequest is request type for the Query/QueryDenomByName RPC
 * method.
 *
 * @generated from message dysonprotocol.nameservice.v1.QueryDenomByNameRequest
 */
export class QueryDenomByNameRequest extends Message<QueryDenomByNameRequest> {
  /**
   * name is the root name to list denoms for
   *
   * @generated from field: string name = 1;
   */
  name = "";

  /**
   * subdenom_prefix optionally filters to a sub-path under the name (e.g.
   * "/foo") If empty, all denoms under the root including the base denom are
   * returned
   *
   * @generated from field: string subdenom_prefix = 3;
   */
  subdenomPrefix = "";

  /**
   * pagination defines an optional pagination for the request.
   *
   * @generated from field: cosmos.base.query.v1beta1.PageRequest pagination = 2;
   */
  pagination?: PageRequest;

  constructor(data?: PartialMessage<QueryDenomByNameRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dysonprotocol.nameservice.v1.QueryDenomByNameRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "subdenom_prefix", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "pagination", kind: "message", T: PageRequest },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryDenomByNameRequest {
    return new QueryDenomByNameRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryDenomByNameRequest {
    return new QueryDenomByNameRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryDenomByNameRequest {
    return new QueryDenomByNameRequest().fromJsonString(jsonString, options);
  }

  static equals(a: QueryDenomByNameRequest | PlainMessage<QueryDenomByNameRequest> | undefined, b: QueryDenomByNameRequest | PlainMessage<QueryDenomByNameRequest> | undefined): boolean {
    return proto3.util.equals(QueryDenomByNameRequest, a, b);
  }
}

/**
 * QueryDenomByNameResponse is response type for the
 * Query/QueryDenomByName RPC method.
 *
 * @generated from message dysonprotocol.nameservice.v1.QueryDenomByNameResponse
 */
export class QueryDenomByNameResponse extends Message<QueryDenomByNameResponse> {
  /**
   * denoms is the list of denom details under the provided root name
   *
   * @generated from field: repeated dysonprotocol.nameservice.v1.DenomDetails denoms = 1;
   */
  denoms: DenomDetails[] = [];

  /**
   * pagination defines the pagination in the response.
   *
   * @generated from field: cosmos.base.query.v1beta1.PageResponse pagination = 2;
   */
  pagination?: PageResponse;

  constructor(data?: PartialMessage<QueryDenomByNameResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dysonprotocol.nameservice.v1.QueryDenomByNameResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "denoms", kind: "message", T: DenomDetails, repeated: true },
    { no: 2, name: "pagination", kind: "message", T: PageResponse },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryDenomByNameResponse {
    return new QueryDenomByNameResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryDenomByNameResponse {
    return new QueryDenomByNameResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryDenomByNameResponse {
    return new QueryDenomByNameResponse().fromJsonString(jsonString, options);
  }

  static equals(a: QueryDenomByNameResponse | PlainMessage<QueryDenomByNameResponse> | undefined, b: QueryDenomByNameResponse | PlainMessage<QueryDenomByNameResponse> | undefined): boolean {
    return proto3.util.equals(QueryDenomByNameResponse, a, b);
  }
}

/**
 * QueryBidsByBidderRequest lists bids by bidder with optional status filter
 *
 * @generated from message dysonprotocol.nameservice.v1.QueryBidsByBidderRequest
 */
export class QueryBidsByBidderRequest extends Message<QueryBidsByBidderRequest> {
  /**
   * @generated from field: string bidder = 1;
   */
  bidder = "";

  /**
   * optional
   *
   * @generated from field: repeated dysonprotocol.nameservice.v1.BidStatus status_filter = 2;
   */
  statusFilter: BidStatus[] = [];

  /**
   * @generated from field: cosmos.base.query.v1beta1.PageRequest pagination = 4;
   */
  pagination?: PageRequest;

  constructor(data?: PartialMessage<QueryBidsByBidderRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dysonprotocol.nameservice.v1.QueryBidsByBidderRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "bidder", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "status_filter", kind: "enum", T: proto3.getEnumType(BidStatus), repeated: true },
    { no: 4, name: "pagination", kind: "message", T: PageRequest },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryBidsByBidderRequest {
    return new QueryBidsByBidderRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryBidsByBidderRequest {
    return new QueryBidsByBidderRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryBidsByBidderRequest {
    return new QueryBidsByBidderRequest().fromJsonString(jsonString, options);
  }

  static equals(a: QueryBidsByBidderRequest | PlainMessage<QueryBidsByBidderRequest> | undefined, b: QueryBidsByBidderRequest | PlainMessage<QueryBidsByBidderRequest> | undefined): boolean {
    return proto3.util.equals(QueryBidsByBidderRequest, a, b);
  }
}

/**
 * @generated from message dysonprotocol.nameservice.v1.QueryBidsByBidderResponse
 */
export class QueryBidsByBidderResponse extends Message<QueryBidsByBidderResponse> {
  /**
   * @generated from field: repeated dysonprotocol.nameservice.v1.BidWithNFTStatus bids = 1;
   */
  bids: BidWithNFTStatus[] = [];

  /**
   * @generated from field: cosmos.base.query.v1beta1.PageResponse pagination = 2;
   */
  pagination?: PageResponse;

  constructor(data?: PartialMessage<QueryBidsByBidderResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dysonprotocol.nameservice.v1.QueryBidsByBidderResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "bids", kind: "message", T: BidWithNFTStatus, repeated: true },
    { no: 2, name: "pagination", kind: "message", T: PageResponse },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryBidsByBidderResponse {
    return new QueryBidsByBidderResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryBidsByBidderResponse {
    return new QueryBidsByBidderResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryBidsByBidderResponse {
    return new QueryBidsByBidderResponse().fromJsonString(jsonString, options);
  }

  static equals(a: QueryBidsByBidderResponse | PlainMessage<QueryBidsByBidderResponse> | undefined, b: QueryBidsByBidderResponse | PlainMessage<QueryBidsByBidderResponse> | undefined): boolean {
    return proto3.util.equals(QueryBidsByBidderResponse, a, b);
  }
}

/**
 * QueryBidsForNFTRequest lists bids for an NFT
 *
 * @generated from message dysonprotocol.nameservice.v1.QueryBidsForNFTRequest
 */
export class QueryBidsForNFTRequest extends Message<QueryBidsForNFTRequest> {
  /**
   * @generated from field: string class_id = 1;
   */
  classId = "";

  /**
   * @generated from field: string nft_id = 2;
   */
  nftId = "";

  /**
   * @generated from field: cosmos.base.query.v1beta1.PageRequest pagination = 3;
   */
  pagination?: PageRequest;

  constructor(data?: PartialMessage<QueryBidsForNFTRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dysonprotocol.nameservice.v1.QueryBidsForNFTRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "class_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "nft_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "pagination", kind: "message", T: PageRequest },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryBidsForNFTRequest {
    return new QueryBidsForNFTRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryBidsForNFTRequest {
    return new QueryBidsForNFTRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryBidsForNFTRequest {
    return new QueryBidsForNFTRequest().fromJsonString(jsonString, options);
  }

  static equals(a: QueryBidsForNFTRequest | PlainMessage<QueryBidsForNFTRequest> | undefined, b: QueryBidsForNFTRequest | PlainMessage<QueryBidsForNFTRequest> | undefined): boolean {
    return proto3.util.equals(QueryBidsForNFTRequest, a, b);
  }
}

/**
 * @generated from message dysonprotocol.nameservice.v1.QueryBidsForNFTResponse
 */
export class QueryBidsForNFTResponse extends Message<QueryBidsForNFTResponse> {
  /**
   * @generated from field: repeated dysonprotocol.nameservice.v1.BidRecord bids = 1;
   */
  bids: BidRecord[] = [];

  /**
   * @generated from field: cosmos.base.query.v1beta1.PageResponse pagination = 2;
   */
  pagination?: PageResponse;

  constructor(data?: PartialMessage<QueryBidsForNFTResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dysonprotocol.nameservice.v1.QueryBidsForNFTResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "bids", kind: "message", T: BidRecord, repeated: true },
    { no: 2, name: "pagination", kind: "message", T: PageResponse },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryBidsForNFTResponse {
    return new QueryBidsForNFTResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryBidsForNFTResponse {
    return new QueryBidsForNFTResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryBidsForNFTResponse {
    return new QueryBidsForNFTResponse().fromJsonString(jsonString, options);
  }

  static equals(a: QueryBidsForNFTResponse | PlainMessage<QueryBidsForNFTResponse> | undefined, b: QueryBidsForNFTResponse | PlainMessage<QueryBidsForNFTResponse> | undefined): boolean {
    return proto3.util.equals(QueryBidsForNFTResponse, a, b);
  }
}

