// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts"
// @generated from file ibc/core/client/v2/query.proto (package ibc.core.client.v2, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { QueryConfigRequest, QueryConfigResponse, QueryCounterpartyInfoRequest, QueryCounterpartyInfoResponse } from "./query_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * Query provides defines the gRPC querier service
 *
 * @generated from service ibc.core.client.v2.Query
 */
export const Query = {
  typeName: "ibc.core.client.v2.Query",
  methods: {
    /**
     * CounterpartyInfo queries an IBC light counter party info.
     *
     * @generated from rpc ibc.core.client.v2.Query.CounterpartyInfo
     */
    counterpartyInfo: {
      name: "CounterpartyInfo",
      I: QueryCounterpartyInfoRequest,
      O: QueryCounterpartyInfoResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Config queries the IBC client v2 configuration for a given client.
     *
     * @generated from rpc ibc.core.client.v2.Query.Config
     */
    config: {
      name: "Config",
      I: QueryConfigRequest,
      O: QueryConfigResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

