// @generated by protoc-gen-es v2.9.0 with parameter "target=ts"
// @generated from file ibc/core/client/v2/tx.proto (package ibc.core.client.v2, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_cosmos_msg_v1_msg } from "../../../../cosmos/msg/v1/msg_pb";
import { file_gogoproto_gogo } from "../../../../gogoproto/gogo_pb";
import type { Config } from "./config_pb";
import { file_ibc_core_client_v2_config } from "./config_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file ibc/core/client/v2/tx.proto.
 */
export const file_ibc_core_client_v2_tx: GenFile = /*@__PURE__*/
  fileDesc("ChtpYmMvY29yZS9jbGllbnQvdjIvdHgucHJvdG8SEmliYy5jb3JlLmNsaWVudC52MiKRAQoXTXNnUmVnaXN0ZXJDb3VudGVycGFydHkSEQoJY2xpZW50X2lkGAEgASgJEiIKGmNvdW50ZXJwYXJ0eV9tZXJrbGVfcHJlZml4GAIgAygMEh4KFmNvdW50ZXJwYXJ0eV9jbGllbnRfaWQYAyABKAkSDgoGc2lnbmVyGAQgASgJOg+IoB8AguewKgZzaWduZXIiIQofTXNnUmVnaXN0ZXJDb3VudGVycGFydHlSZXNwb25zZSJ9ChVNc2dVcGRhdGVDbGllbnRDb25maWcSEQoJY2xpZW50X2lkGAEgASgJEjAKBmNvbmZpZxgCIAEoCzIaLmliYy5jb3JlLmNsaWVudC52Mi5Db25maWdCBMjeHwASDgoGc2lnbmVyGAMgASgJOg+IoB8AguewKgZzaWduZXIiHwodTXNnVXBkYXRlQ2xpZW50Q29uZmlnUmVzcG9uc2Uy+gEKA01zZxJ4ChRSZWdpc3RlckNvdW50ZXJwYXJ0eRIrLmliYy5jb3JlLmNsaWVudC52Mi5Nc2dSZWdpc3RlckNvdW50ZXJwYXJ0eRozLmliYy5jb3JlLmNsaWVudC52Mi5Nc2dSZWdpc3RlckNvdW50ZXJwYXJ0eVJlc3BvbnNlEnIKElVwZGF0ZUNsaWVudENvbmZpZxIpLmliYy5jb3JlLmNsaWVudC52Mi5Nc2dVcGRhdGVDbGllbnRDb25maWcaMS5pYmMuY29yZS5jbGllbnQudjIuTXNnVXBkYXRlQ2xpZW50Q29uZmlnUmVzcG9uc2UaBYDnsCoBQsoBChZjb20uaWJjLmNvcmUuY2xpZW50LnYyQgdUeFByb3RvUAFaPGdpdGh1Yi5jb20vY29zbW9zL2liYy1nby92MTAvbW9kdWxlcy9jb3JlLzAyLWNsaWVudC92Mi90eXBlc6ICA0lDQ6oCEkliYy5Db3JlLkNsaWVudC5WMsoCEkliY1xDb3JlXENsaWVudFxWMuICHkliY1xDb3JlXENsaWVudFxWMlxHUEJNZXRhZGF0YeoCFUliYzo6Q29yZTo6Q2xpZW50OjpWMmIGcHJvdG8z", [file_cosmos_msg_v1_msg, file_gogoproto_gogo, file_ibc_core_client_v2_config]);

/**
 * MsgRegisterCounterparty defines a message to register a counterparty on a
 * client
 *
 * @generated from message ibc.core.client.v2.MsgRegisterCounterparty
 */
export type MsgRegisterCounterparty = Message<"ibc.core.client.v2.MsgRegisterCounterparty"> & {
  /**
   * client identifier
   *
   * @generated from field: string client_id = 1;
   */
  clientId: string;

  /**
   * counterparty merkle prefix
   *
   * @generated from field: repeated bytes counterparty_merkle_prefix = 2;
   */
  counterpartyMerklePrefix: Uint8Array[];

  /**
   * counterparty client identifier
   *
   * @generated from field: string counterparty_client_id = 3;
   */
  counterpartyClientId: string;

  /**
   * signer address
   *
   * @generated from field: string signer = 4;
   */
  signer: string;
};

/**
 * Describes the message ibc.core.client.v2.MsgRegisterCounterparty.
 * Use `create(MsgRegisterCounterpartySchema)` to create a new message.
 */
export const MsgRegisterCounterpartySchema: GenMessage<MsgRegisterCounterparty> = /*@__PURE__*/
  messageDesc(file_ibc_core_client_v2_tx, 0);

/**
 * MsgRegisterCounterpartyResponse defines the Msg/RegisterCounterparty response
 * type.
 *
 * @generated from message ibc.core.client.v2.MsgRegisterCounterpartyResponse
 */
export type MsgRegisterCounterpartyResponse = Message<"ibc.core.client.v2.MsgRegisterCounterpartyResponse"> & {
};

/**
 * Describes the message ibc.core.client.v2.MsgRegisterCounterpartyResponse.
 * Use `create(MsgRegisterCounterpartyResponseSchema)` to create a new message.
 */
export const MsgRegisterCounterpartyResponseSchema: GenMessage<MsgRegisterCounterpartyResponse> = /*@__PURE__*/
  messageDesc(file_ibc_core_client_v2_tx, 1);

/**
 * MsgUpdateClientConfig defines the sdk.Msg type to update the configuration
 * for a given client
 *
 * @generated from message ibc.core.client.v2.MsgUpdateClientConfig
 */
export type MsgUpdateClientConfig = Message<"ibc.core.client.v2.MsgUpdateClientConfig"> & {
  /**
   * client identifier
   *
   * @generated from field: string client_id = 1;
   */
  clientId: string;

  /**
   * allowed relayers
   *
   * NOTE: All fields in the config must be supplied.
   *
   * @generated from field: ibc.core.client.v2.Config config = 2;
   */
  config?: Config;

  /**
   * signer address
   *
   * @generated from field: string signer = 3;
   */
  signer: string;
};

/**
 * Describes the message ibc.core.client.v2.MsgUpdateClientConfig.
 * Use `create(MsgUpdateClientConfigSchema)` to create a new message.
 */
export const MsgUpdateClientConfigSchema: GenMessage<MsgUpdateClientConfig> = /*@__PURE__*/
  messageDesc(file_ibc_core_client_v2_tx, 2);

/**
 * MsgUpdateClientConfigResponse defines the MsgUpdateClientConfig response
 * type.
 *
 * @generated from message ibc.core.client.v2.MsgUpdateClientConfigResponse
 */
export type MsgUpdateClientConfigResponse = Message<"ibc.core.client.v2.MsgUpdateClientConfigResponse"> & {
};

/**
 * Describes the message ibc.core.client.v2.MsgUpdateClientConfigResponse.
 * Use `create(MsgUpdateClientConfigResponseSchema)` to create a new message.
 */
export const MsgUpdateClientConfigResponseSchema: GenMessage<MsgUpdateClientConfigResponse> = /*@__PURE__*/
  messageDesc(file_ibc_core_client_v2_tx, 3);

/**
 * Msg defines the ibc/client/v2 Msg service.
 *
 * @generated from service ibc.core.client.v2.Msg
 */
export const Msg: GenService<{
  /**
   * RegisterCounterparty defines a rpc handler method for
   * MsgRegisterCounterparty.
   *
   * @generated from rpc ibc.core.client.v2.Msg.RegisterCounterparty
   */
  registerCounterparty: {
    methodKind: "unary";
    input: typeof MsgRegisterCounterpartySchema;
    output: typeof MsgRegisterCounterpartyResponseSchema;
  },
  /**
   * UpdateClientConfig defines a rpc handler method for MsgUpdateClientConfig.
   *
   * @generated from rpc ibc.core.client.v2.Msg.UpdateClientConfig
   */
  updateClientConfig: {
    methodKind: "unary";
    input: typeof MsgUpdateClientConfigSchema;
    output: typeof MsgUpdateClientConfigResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_ibc_core_client_v2_tx, 0);

