// @generated by protoc-gen-es v2.9.0 with parameter "target=ts"
// @generated from file dysonprotocol/nft/module/v1/module.proto (package dysonprotocol.nft.module.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_cosmos_app_v1alpha1_module } from "../../../../cosmos/app/v1alpha1/module_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file dysonprotocol/nft/module/v1/module.proto.
 */
export const file_dysonprotocol_nft_module_v1_module: GenFile = /*@__PURE__*/
  fileDesc("CihkeXNvbnByb3RvY29sL25mdC9tb2R1bGUvdjEvbW9kdWxlLnByb3RvEhtkeXNvbnByb3RvY29sLm5mdC5tb2R1bGUudjEiMwoGTW9kdWxlOim6wJbaASMKIWR5c29ucHJvdG9jb2wuY29tL3gvbmZ0L21vZHVsZS92MULnAQofY29tLmR5c29ucHJvdG9jb2wubmZ0Lm1vZHVsZS52MUILTW9kdWxlUHJvdG9QAVooZHlzb25wcm90b2NvbC5jb20veC9uZnQvbW9kdWxlL3YxO21vZHVsZaICA0ROTaoCG0R5c29ucHJvdG9jb2wuTmZ0Lk1vZHVsZS5WMcoCG0R5c29ucHJvdG9jb2xcTmZ0XE1vZHVsZVxWMeICJ0R5c29ucHJvdG9jb2xcTmZ0XE1vZHVsZVxWMVxHUEJNZXRhZGF0YeoCHkR5c29ucHJvdG9jb2w6Ok5mdDo6TW9kdWxlOjpWMWIGcHJvdG8z", [file_cosmos_app_v1alpha1_module]);

/**
 * Module is the config object of the nft module.
 *
 * @generated from message dysonprotocol.nft.module.v1.Module
 */
export type Module = Message<"dysonprotocol.nft.module.v1.Module"> & {
};

/**
 * Describes the message dysonprotocol.nft.module.v1.Module.
 * Use `create(ModuleSchema)` to create a new message.
 */
export const ModuleSchema: GenMessage<Module> = /*@__PURE__*/
  messageDesc(file_dysonprotocol_nft_module_v1_module, 0);

