// @generated by protoc-gen-es v2.9.0 with parameter "target=ts"
// @generated from file dysonprotocol/nft/v1beta1/nft.proto (package dysonprotocol.nft.v1beta1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Any } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_any } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file dysonprotocol/nft/v1beta1/nft.proto.
 */
export const file_dysonprotocol_nft_v1beta1_nft: GenFile = /*@__PURE__*/
  fileDesc("CiNkeXNvbnByb3RvY29sL25mdC92MWJldGExL25mdC5wcm90bxIZZHlzb25wcm90b2NvbC5uZnQudjFiZXRhMSKJAQoFQ2xhc3MSCgoCaWQYASABKAkSDAoEbmFtZRgCIAEoCRIOCgZzeW1ib2wYAyABKAkSEwoLZGVzY3JpcHRpb24YBCABKAkSCwoDdXJpGAUgASgJEhAKCHVyaV9oYXNoGAYgASgJEiIKBGRhdGEYByABKAsyFC5nb29nbGUucHJvdG9idWYuQW55ImYKA05GVBIQCghjbGFzc19pZBgBIAEoCRIKCgJpZBgCIAEoCRILCgN1cmkYAyABKAkSEAoIdXJpX2hhc2gYBCABKAkSIgoEZGF0YRgKIAEoCzIULmdvb2dsZS5wcm90b2J1Zi5BbnlCyAEKHWNvbS5keXNvbnByb3RvY29sLm5mdC52MWJldGExQghOZnRQcm90b1ABWhdkeXNvbnByb3RvY29sLmNvbS94L25mdKICA0ROWKoCGUR5c29ucHJvdG9jb2wuTmZ0LlYxYmV0YTHKAhlEeXNvbnByb3RvY29sXE5mdFxWMWJldGEx4gIlRHlzb25wcm90b2NvbFxOZnRcVjFiZXRhMVxHUEJNZXRhZGF0YeoCG0R5c29ucHJvdG9jb2w6Ok5mdDo6VjFiZXRhMWIGcHJvdG8z", [file_google_protobuf_any]);

/**
 * Class defines the class of the nft type.
 *
 * Whaleswap notes:
 * - Auction escrows may be represented by NFTs whose (class_id, id) pair is
 *   referenced by auction records. Query endpoints such as AuctionByNFT use
 *   this identity to locate the escrow state.
 *
 * @generated from message dysonprotocol.nft.v1beta1.Class
 */
export type Class = Message<"dysonprotocol.nft.v1beta1.Class"> & {
  /**
   * id defines the unique identifier of the NFT classification, similar to the
   * contract address of ERC721
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * name defines the human-readable name of the NFT classification. Optional
   *
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * symbol is an abbreviated name for nft classification. Optional
   *
   * @generated from field: string symbol = 3;
   */
  symbol: string;

  /**
   * description is a brief description of nft classification. Optional
   *
   * @generated from field: string description = 4;
   */
  description: string;

  /**
   * uri for the class metadata stored off chain. It can define schema for Class
   * and NFT `Data` attributes. Optional
   *
   * @generated from field: string uri = 5;
   */
  uri: string;

  /**
   * uri_hash is a hash of the document pointed by uri. Optional
   *
   * @generated from field: string uri_hash = 6;
   */
  uriHash: string;

  /**
   * data is the app specific metadata of the NFT class. Optional
   *
   * @generated from field: google.protobuf.Any data = 7;
   */
  data?: Any;
};

/**
 * Describes the message dysonprotocol.nft.v1beta1.Class.
 * Use `create(ClassSchema)` to create a new message.
 */
export const ClassSchema: GenMessage<Class> = /*@__PURE__*/
  messageDesc(file_dysonprotocol_nft_v1beta1_nft, 0);

/**
 * NFT defines the NFT.
 *
 * - When used with whaleswap auctions, the (class_id, id) uniquely identifies
 *   the escrow marker that controls redemption of the locked sell coin.
 *
 * @generated from message dysonprotocol.nft.v1beta1.NFT
 */
export type NFT = Message<"dysonprotocol.nft.v1beta1.NFT"> & {
  /**
   * class_id associated with the NFT, similar to the contract address of ERC721
   *
   * @generated from field: string class_id = 1;
   */
  classId: string;

  /**
   * id is a unique identifier of the NFT
   *
   * @generated from field: string id = 2;
   */
  id: string;

  /**
   * uri for the NFT metadata stored off chain
   *
   * @generated from field: string uri = 3;
   */
  uri: string;

  /**
   * uri_hash is a hash of the document pointed by uri
   *
   * @generated from field: string uri_hash = 4;
   */
  uriHash: string;

  /**
   * data is an app specific data of the NFT. Optional
   *
   * @generated from field: google.protobuf.Any data = 10;
   */
  data?: Any;
};

/**
 * Describes the message dysonprotocol.nft.v1beta1.NFT.
 * Use `create(NFTSchema)` to create a new message.
 */
export const NFTSchema: GenMessage<NFT> = /*@__PURE__*/
  messageDesc(file_dysonprotocol_nft_v1beta1_nft, 1);

