// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts"
// @generated from file dysonprotocol/nft/v1beta1/tx.proto (package dysonprotocol.nft.v1beta1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { MsgSend, MsgSendResponse } from "./tx_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * Msg defines the nft Msg service.
 *
 * @generated from service dysonprotocol.nft.v1beta1.Msg
 */
export const Msg = {
  typeName: "dysonprotocol.nft.v1beta1.Msg",
  methods: {
    /**
     * Send defines a method to send a nft from one account to another account.
     *
     * @generated from rpc dysonprotocol.nft.v1beta1.Msg.Send
     */
    send: {
      name: "Send",
      I: MsgSend,
      O: MsgSendResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

