// @generated by protoc-gen-es v2.9.0 with parameter "target=ts"
// @generated from file ibc/core/channel/v2/genesis.proto (package ibc.core.channel.v2, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_gogoproto_gogo } from "../../../../gogoproto/gogo_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file ibc/core/channel/v2/genesis.proto.
 */
export const file_ibc_core_channel_v2_genesis: GenFile = /*@__PURE__*/
  fileDesc("CiFpYmMvY29yZS9jaGFubmVsL3YyL2dlbmVzaXMucHJvdG8SE2liYy5jb3JlLmNoYW5uZWwudjIiyQIKDEdlbmVzaXNTdGF0ZRJAChBhY2tub3dsZWRnZW1lbnRzGAIgAygLMiAuaWJjLmNvcmUuY2hhbm5lbC52Mi5QYWNrZXRTdGF0ZUIEyN4fABI7Cgtjb21taXRtZW50cxgDIAMoCzIgLmliYy5jb3JlLmNoYW5uZWwudjIuUGFja2V0U3RhdGVCBMjeHwASOAoIcmVjZWlwdHMYBCADKAsyIC5pYmMuY29yZS5jaGFubmVsLnYyLlBhY2tldFN0YXRlQgTI3h8AEj0KDWFzeW5jX3BhY2tldHMYBSADKAsyIC5pYmMuY29yZS5jaGFubmVsLnYyLlBhY2tldFN0YXRlQgTI3h8AEkEKDnNlbmRfc2VxdWVuY2VzGAYgAygLMiMuaWJjLmNvcmUuY2hhbm5lbC52Mi5QYWNrZXRTZXF1ZW5jZUIEyN4fACJGCgtQYWNrZXRTdGF0ZRIRCgljbGllbnRfaWQYASABKAkSEAoIc2VxdWVuY2UYAiABKAQSDAoEZGF0YRgDIAEoDDoEiKAfACI1Cg5QYWNrZXRTZXF1ZW5jZRIRCgljbGllbnRfaWQYASABKAkSEAoIc2VxdWVuY2UYAiABKARC1QEKF2NvbS5pYmMuY29yZS5jaGFubmVsLnYyQgxHZW5lc2lzUHJvdG9QAVo9Z2l0aHViLmNvbS9jb3Ntb3MvaWJjLWdvL3YxMC9tb2R1bGVzL2NvcmUvMDQtY2hhbm5lbC92Mi90eXBlc6ICA0lDQ6oCE0liYy5Db3JlLkNoYW5uZWwuVjLKAhNJYmNcQ29yZVxDaGFubmVsXFYy4gIfSWJjXENvcmVcQ2hhbm5lbFxWMlxHUEJNZXRhZGF0YeoCFkliYzo6Q29yZTo6Q2hhbm5lbDo6VjJiBnByb3RvMw", [file_gogoproto_gogo]);

/**
 * GenesisState defines the ibc channel/v2 submodule's genesis state.
 *
 * @generated from message ibc.core.channel.v2.GenesisState
 */
export type GenesisState = Message<"ibc.core.channel.v2.GenesisState"> & {
  /**
   * @generated from field: repeated ibc.core.channel.v2.PacketState acknowledgements = 2;
   */
  acknowledgements: PacketState[];

  /**
   * @generated from field: repeated ibc.core.channel.v2.PacketState commitments = 3;
   */
  commitments: PacketState[];

  /**
   * @generated from field: repeated ibc.core.channel.v2.PacketState receipts = 4;
   */
  receipts: PacketState[];

  /**
   * @generated from field: repeated ibc.core.channel.v2.PacketState async_packets = 5;
   */
  asyncPackets: PacketState[];

  /**
   * @generated from field: repeated ibc.core.channel.v2.PacketSequence send_sequences = 6;
   */
  sendSequences: PacketSequence[];
};

/**
 * Describes the message ibc.core.channel.v2.GenesisState.
 * Use `create(GenesisStateSchema)` to create a new message.
 */
export const GenesisStateSchema: GenMessage<GenesisState> = /*@__PURE__*/
  messageDesc(file_ibc_core_channel_v2_genesis, 0);

/**
 * PacketState defines the generic type necessary to retrieve and store
 * packet commitments, acknowledgements, and receipts.
 * Caller is responsible for knowing the context necessary to interpret this
 * state as a commitment, acknowledgement, or a receipt.
 *
 * @generated from message ibc.core.channel.v2.PacketState
 */
export type PacketState = Message<"ibc.core.channel.v2.PacketState"> & {
  /**
   * client unique identifier.
   *
   * @generated from field: string client_id = 1;
   */
  clientId: string;

  /**
   * packet sequence.
   *
   * @generated from field: uint64 sequence = 2;
   */
  sequence: bigint;

  /**
   * embedded data that represents packet state.
   *
   * @generated from field: bytes data = 3;
   */
  data: Uint8Array;
};

/**
 * Describes the message ibc.core.channel.v2.PacketState.
 * Use `create(PacketStateSchema)` to create a new message.
 */
export const PacketStateSchema: GenMessage<PacketState> = /*@__PURE__*/
  messageDesc(file_ibc_core_channel_v2_genesis, 1);

/**
 * PacketSequence defines the genesis type necessary to retrieve and store next
 * send sequences.
 *
 * @generated from message ibc.core.channel.v2.PacketSequence
 */
export type PacketSequence = Message<"ibc.core.channel.v2.PacketSequence"> & {
  /**
   * client unique identifier.
   *
   * @generated from field: string client_id = 1;
   */
  clientId: string;

  /**
   * packet sequence
   *
   * @generated from field: uint64 sequence = 2;
   */
  sequence: bigint;
};

/**
 * Describes the message ibc.core.channel.v2.PacketSequence.
 * Use `create(PacketSequenceSchema)` to create a new message.
 */
export const PacketSequenceSchema: GenMessage<PacketSequence> = /*@__PURE__*/
  messageDesc(file_ibc_core_channel_v2_genesis, 2);

