// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file dysonprotocol/whaleswap/v1/leverage.proto (package dysonprotocol.whaleswap.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64, Timestamp } from "@bufbuild/protobuf";
import { Coin, DecCoin } from "../../../cosmos/base/v1beta1/coin_pb.js";

/**
 * @generated from enum dysonprotocol.whaleswap.v1.LiquidationStatus
 */
export enum LiquidationStatus {
  /**
   * @generated from enum value: LIQUIDATION_STATUS_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: LIQUIDATION_STATUS_NONE = 1;
   */
  NONE = 1,

  /**
   * @generated from enum value: LIQUIDATION_STATUS_INITIALIZED = 2;
   */
  INITIALIZED = 2,
}
// Retrieve enum metadata with: proto3.getEnumType(LiquidationStatus)
proto3.util.setEnumType(LiquidationStatus, "dysonprotocol.whaleswap.v1.LiquidationStatus", [
  { no: 0, name: "LIQUIDATION_STATUS_UNSPECIFIED" },
  { no: 1, name: "LIQUIDATION_STATUS_NONE" },
  { no: 2, name: "LIQUIDATION_STATUS_INITIALIZED" },
]);

/**
 * @generated from enum dysonprotocol.whaleswap.v1.PositionStatus
 */
export enum PositionStatus {
  /**
   * @generated from enum value: POSITION_STATUS_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: POSITION_STATUS_OPEN = 1;
   */
  OPEN = 1,

  /**
   * @generated from enum value: POSITION_STATUS_CLOSED = 2;
   */
  CLOSED = 2,

  /**
   * @generated from enum value: POSITION_STATUS_LIQUIDATING = 3;
   */
  LIQUIDATING = 3,

  /**
   * @generated from enum value: POSITION_STATUS_LIQUIDATED = 4;
   */
  LIQUIDATED = 4,
}
// Retrieve enum metadata with: proto3.getEnumType(PositionStatus)
proto3.util.setEnumType(PositionStatus, "dysonprotocol.whaleswap.v1.PositionStatus", [
  { no: 0, name: "POSITION_STATUS_UNSPECIFIED" },
  { no: 1, name: "POSITION_STATUS_OPEN" },
  { no: 2, name: "POSITION_STATUS_CLOSED" },
  { no: 3, name: "POSITION_STATUS_LIQUIDATING" },
  { no: 4, name: "POSITION_STATUS_LIQUIDATED" },
]);

/**
 * LeveragePosition represents an active leverage position for a trader.
 *
 * @generated from message dysonprotocol.whaleswap.v1.LeveragePosition
 */
export class LeveragePosition extends Message<LeveragePosition> {
  /**
   * @generated from field: uint64 position_id = 1;
   */
  positionId = protoInt64.zero;

  /**
   * @generated from field: uint64 pool_id = 2;
   */
  poolId = protoInt64.zero;

  /**
   * @generated from field: string user = 3;
   */
  user = "";

  /**
   * @generated from field: dysonprotocol.whaleswap.v1.PositionStatus status = 4;
   */
  status = PositionStatus.UNSPECIFIED;

  /**
   * @generated from field: cosmos.base.v1beta1.Coin borrowed = 5;
   */
  borrowed?: Coin;

  /**
   * @generated from field: cosmos.base.v1beta1.Coin held = 6;
   */
  held?: Coin;

  /**
   * @generated from field: cosmos.base.v1beta1.Coin collateral = 7;
   */
  collateral?: Coin;

  /**
   * @generated from field: google.protobuf.Timestamp borrow_time = 8;
   */
  borrowTime?: Timestamp;

  /**
   * @generated from field: uint64 created_block_height = 9;
   */
  createdBlockHeight = protoInt64.zero;

  /**
   * @generated from field: uint64 liquidation_initialized_block_height = 10;
   */
  liquidationInitializedBlockHeight = protoInt64.zero;

  /**
   * @generated from field: dysonprotocol.whaleswap.v1.LiquidationStatus liquidation_status = 11;
   */
  liquidationStatus = LiquidationStatus.UNSPECIFIED;

  /**
   * @generated from field: cosmos.base.v1beta1.Coin accrued_interest = 12;
   */
  accruedInterest?: Coin;

  /**
   * ═════ PER-POSITION SNAPSHOTS (sticky to this position) ═════
   * Annual interest rates per reserve denom (exactly two, canonical order).
   * Each amount is a LegacyDec string representing APR (per-year accrual).
   *
   * @generated from field: repeated cosmos.base.v1beta1.DecCoin interest_rate = 22;
   */
  interestRate: DecCoin[] = [];

  /**
   * Minimum collateral ratio used for health/liquidation checks (cosmos.Dec
   * string).
   *
   * @generated from field: string min_collateral_ratio = 23;
   */
  minCollateralRatio = "";

  /**
   * Liquidation threshold used for liquidation checks (cosmos.Dec string).
   *
   * @generated from field: string liquidation_threshold = 24;
   */
  liquidationThreshold = "";

  constructor(data?: PartialMessage<LeveragePosition>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dysonprotocol.whaleswap.v1.LeveragePosition";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "position_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 2, name: "pool_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 3, name: "user", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "status", kind: "enum", T: proto3.getEnumType(PositionStatus) },
    { no: 5, name: "borrowed", kind: "message", T: Coin },
    { no: 6, name: "held", kind: "message", T: Coin },
    { no: 7, name: "collateral", kind: "message", T: Coin },
    { no: 8, name: "borrow_time", kind: "message", T: Timestamp },
    { no: 9, name: "created_block_height", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 10, name: "liquidation_initialized_block_height", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 11, name: "liquidation_status", kind: "enum", T: proto3.getEnumType(LiquidationStatus) },
    { no: 12, name: "accrued_interest", kind: "message", T: Coin },
    { no: 22, name: "interest_rate", kind: "message", T: DecCoin, repeated: true },
    { no: 23, name: "min_collateral_ratio", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 24, name: "liquidation_threshold", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): LeveragePosition {
    return new LeveragePosition().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): LeveragePosition {
    return new LeveragePosition().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): LeveragePosition {
    return new LeveragePosition().fromJsonString(jsonString, options);
  }

  static equals(a: LeveragePosition | PlainMessage<LeveragePosition> | undefined, b: LeveragePosition | PlainMessage<LeveragePosition> | undefined): boolean {
    return proto3.util.equals(LeveragePosition, a, b);
  }
}

