// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file dysonprotocol/whaleswap/v1/params.proto (package dysonprotocol.whaleswap.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Duration, Message, proto3, protoInt64 } from "@bufbuild/protobuf";
import { Coin } from "../../../cosmos/base/v1beta1/coin_pb.js";

/**
 * ArbitrageMode determines how the protocol handles arbitrage opportunities.
 *
 * @generated from enum dysonprotocol.whaleswap.v1.ArbitrageMode
 */
export enum ArbitrageMode {
  /**
   * ARBITRAGE_MODE_UNSPECIFIED defaults to AUTO for backwards compatibility.
   *
   * @generated from enum value: ARBITRAGE_MODE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * ARBITRAGE_MODE_DISABLED completely disables arbitrage detection and
   * execution.
   *
   * @generated from enum value: ARBITRAGE_MODE_DISABLED = 1;
   */
  DISABLED = 1,

  /**
   * ARBITRAGE_MODE_MANUAL allows arbitrage queries/simulation but no automatic
   * execution.
   *
   * @generated from enum value: ARBITRAGE_MODE_MANUAL = 2;
   */
  MANUAL = 2,

  /**
   * ARBITRAGE_MODE_AUTO enables automatic arbitrage execution after trades.
   *
   * @generated from enum value: ARBITRAGE_MODE_AUTO = 3;
   */
  AUTO = 3,
}
// Retrieve enum metadata with: proto3.getEnumType(ArbitrageMode)
proto3.util.setEnumType(ArbitrageMode, "dysonprotocol.whaleswap.v1.ArbitrageMode", [
  { no: 0, name: "ARBITRAGE_MODE_UNSPECIFIED" },
  { no: 1, name: "ARBITRAGE_MODE_DISABLED" },
  { no: 2, name: "ARBITRAGE_MODE_MANUAL" },
  { no: 3, name: "ARBITRAGE_MODE_AUTO" },
]);

/**
 * @generated from message dysonprotocol.whaleswap.v1.Params
 */
export class Params extends Message<Params> {
  /**
   * pfand_per_offer is the PFAND coin required for liquid-mode offers.
   *
   * @generated from field: cosmos.base.v1beta1.Coin pfand_per_offer = 1;
   */
  pfandPerOffer?: Coin;

  /**
   * valuation_fee_pct is the percentage applied per valuation_period.
   *
   * @generated from field: string valuation_fee_pct = 2;
   */
  valuationFeePct = "";

  /**
   * valuation_period defines the time duration to which valuation_fee_pct
   * applies.
   *
   * @generated from field: google.protobuf.Duration valuation_period = 3;
   */
  valuationPeriod?: Duration;

  /**
   * bid_timeout defines the minimum duration a placed bid must remain pending
   * before it can be claimed by the bidder.
   *
   * @generated from field: google.protobuf.Duration bid_timeout = 4;
   */
  bidTimeout?: Duration;

  /**
   * minimum_bid_percent_increase specifies the minimum percent increase
   * required over the current valuation for a new bid to be accepted.
   *
   * @generated from field: string minimum_bid_percent_increase = 5;
   */
  minimumBidPercentIncrease = "";

  /**
   * @generated from field: uint32 max_note_length = 6;
   */
  maxNoteLength = 0;

  /**
   * ═════ LEVERAGE PARAMETERS ═════
   * Block delay before position owner can close position
   *
   * @generated from field: uint64 block_delay_before_close = 7;
   */
  blockDelayBeforeClose = protoInt64.zero;

  /**
   * Block delay before liquidation can be finalized after initialization
   *
   * @generated from field: uint64 block_delay_before_liquidation = 8;
   */
  blockDelayBeforeLiquidation = protoInt64.zero;

  /**
   * ═════ ARBITRAGE PARAMETERS ═════
   * arbitrage_mode controls protocol arbitrage behavior.
   *
   * @generated from field: dysonprotocol.whaleswap.v1.ArbitrageMode arbitrage_mode = 9;
   */
  arbitrageMode = ArbitrageMode.UNSPECIFIED;

  constructor(data?: PartialMessage<Params>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dysonprotocol.whaleswap.v1.Params";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "pfand_per_offer", kind: "message", T: Coin },
    { no: 2, name: "valuation_fee_pct", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "valuation_period", kind: "message", T: Duration },
    { no: 4, name: "bid_timeout", kind: "message", T: Duration },
    { no: 5, name: "minimum_bid_percent_increase", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "max_note_length", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 7, name: "block_delay_before_close", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 8, name: "block_delay_before_liquidation", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 9, name: "arbitrage_mode", kind: "enum", T: proto3.getEnumType(ArbitrageMode) },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Params {
    return new Params().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Params {
    return new Params().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Params {
    return new Params().fromJsonString(jsonString, options);
  }

  static equals(a: Params | PlainMessage<Params> | undefined, b: Params | PlainMessage<Params> | undefined): boolean {
    return proto3.util.equals(Params, a, b);
  }
}

