// @generated by protoc-gen-es v2.9.0 with parameter "target=ts"
// @generated from file dysonprotocol/whaleswap/v1/params.proto (package dysonprotocol.whaleswap.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_gogoproto_gogo } from "../../../gogoproto/gogo_pb";
import { file_cosmos_proto_cosmos } from "../../../cosmos_proto/cosmos_pb";
import type { Duration } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_duration } from "@bufbuild/protobuf/wkt";
import type { Coin } from "../../../cosmos/base/v1beta1/coin_pb";
import { file_cosmos_base_v1beta1_coin } from "../../../cosmos/base/v1beta1/coin_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file dysonprotocol/whaleswap/v1/params.proto.
 */
export const file_dysonprotocol_whaleswap_v1_params: GenFile = /*@__PURE__*/
  fileDesc("CidkeXNvbnByb3RvY29sL3doYWxlc3dhcC92MS9wYXJhbXMucHJvdG8SGmR5c29ucHJvdG9jb2wud2hhbGVzd2FwLnYxIt8DCgZQYXJhbXMSUgoPcGZhbmRfcGVyX29mZmVyGAEgASgLMhkuY29zbW9zLmJhc2UudjFiZXRhMS5Db2luQh7I3h8A8t4fFnlhbWw6InBmYW5kX3Blcl9vZmZlciISRQoRdmFsdWF0aW9uX2ZlZV9wY3QYAiABKAlCKvLeHxh5YW1sOiJ2YWx1YXRpb25fZmVlX3BjdCLStC0KY29zbW9zLkRlYxJYChB2YWx1YXRpb25fcGVyaW9kGAMgASgLMhkuZ29vZ2xlLnByb3RvYnVmLkR1cmF0aW9uQiPI3h8A8t4fF3lhbWw6InZhbHVhdGlvbl9wZXJpb2QimN8fARJOCgtiaWRfdGltZW91dBgEIAEoCzIZLmdvb2dsZS5wcm90b2J1Zi5EdXJhdGlvbkIeyN4fAPLeHxJ5YW1sOiJiaWRfdGltZW91dCKY3x8BElsKHG1pbmltdW1fYmlkX3BlcmNlbnRfaW5jcmVhc2UYBSABKAlCNfLeHyN5YW1sOiJtaW5pbXVtX2JpZF9wZXJjZW50X2luY3JlYXNlItK0LQpjb3Ntb3MuRGVjEjMKD21heF9ub3RlX2xlbmd0aBgGIAEoDUIa8t4fFnlhbWw6Im1heF9ub3RlX2xlbmd0aCJC3AEKHmNvbS5keXNvbnByb3RvY29sLndoYWxlc3dhcC52MUILUGFyYW1zUHJvdG9QAVojZHlzb25wcm90b2NvbC5jb20veC93aGFsZXN3YXAvdHlwZXOiAgNEV1iqAhpEeXNvbnByb3RvY29sLldoYWxlc3dhcC5WMcoCGkR5c29ucHJvdG9jb2xcV2hhbGVzd2FwXFYx4gImRHlzb25wcm90b2NvbFxXaGFsZXN3YXBcVjFcR1BCTWV0YWRhdGHqAhxEeXNvbnByb3RvY29sOjpXaGFsZXN3YXA6OlYxYgZwcm90bzM", [file_gogoproto_gogo, file_cosmos_proto_cosmos, file_google_protobuf_duration, file_cosmos_base_v1beta1_coin]);

/**
 * @generated from message dysonprotocol.whaleswap.v1.Params
 */
export type Params = Message<"dysonprotocol.whaleswap.v1.Params"> & {
  /**
   * pfand_per_offer is the PFAND coin required for liquid-mode offers.
   *
   * @generated from field: cosmos.base.v1beta1.Coin pfand_per_offer = 1;
   */
  pfandPerOffer?: Coin;

  /**
   * valuation_fee_pct is the percentage applied per valuation_period.
   *
   * @generated from field: string valuation_fee_pct = 2;
   */
  valuationFeePct: string;

  /**
   * valuation_period defines the time duration to which valuation_fee_pct
   * applies.
   *
   * @generated from field: google.protobuf.Duration valuation_period = 3;
   */
  valuationPeriod?: Duration;

  /**
   * bid_timeout defines the minimum duration a placed bid must remain pending
   * before it can be claimed by the bidder.
   *
   * @generated from field: google.protobuf.Duration bid_timeout = 4;
   */
  bidTimeout?: Duration;

  /**
   * minimum_bid_percent_increase specifies the minimum percent increase
   * required over the current valuation for a new bid to be accepted.
   *
   * @generated from field: string minimum_bid_percent_increase = 5;
   */
  minimumBidPercentIncrease: string;

  /**
   * @generated from field: uint32 max_note_length = 6;
   */
  maxNoteLength: number;
};

/**
 * Describes the message dysonprotocol.whaleswap.v1.Params.
 * Use `create(ParamsSchema)` to create a new message.
 */
export const ParamsSchema: GenMessage<Params> = /*@__PURE__*/
  messageDesc(file_dysonprotocol_whaleswap_v1_params, 0);

