// @generated by protoc-gen-es v2.9.0 with parameter "target=ts"
// @generated from file ibc/core/commitment/v1/commitment.proto (package ibc.core.commitment.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_gogoproto_gogo } from "../../../../gogoproto/gogo_pb";
import type { CommitmentProof } from "../../../../cosmos/ics23/v1/proofs_pb";
import { file_cosmos_ics23_v1_proofs } from "../../../../cosmos/ics23/v1/proofs_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file ibc/core/commitment/v1/commitment.proto.
 */
export const file_ibc_core_commitment_v1_commitment: GenFile = /*@__PURE__*/
  fileDesc("CidpYmMvY29yZS9jb21taXRtZW50L3YxL2NvbW1pdG1lbnQucHJvdG8SFmliYy5jb3JlLmNvbW1pdG1lbnQudjEiIAoKTWVya2xlUm9vdBIMCgRoYXNoGAEgASgMOgSIoB8AIiIKDE1lcmtsZVByZWZpeBISCgprZXlfcHJlZml4GAEgASgMIj8KC01lcmtsZVByb29mEjAKBnByb29mcxgBIAMoCzIgLmNvc21vcy5pY3MyMy52MS5Db21taXRtZW50UHJvb2ZC5wEKGmNvbS5pYmMuY29yZS5jb21taXRtZW50LnYxQg9Db21taXRtZW50UHJvdG9QAVo9Z2l0aHViLmNvbS9jb3Ntb3MvaWJjLWdvL3YxMC9tb2R1bGVzL2NvcmUvMjMtY29tbWl0bWVudC90eXBlc6ICA0lDQ6oCFkliYy5Db3JlLkNvbW1pdG1lbnQuVjHKAhZJYmNcQ29yZVxDb21taXRtZW50XFYx4gIiSWJjXENvcmVcQ29tbWl0bWVudFxWMVxHUEJNZXRhZGF0YeoCGUliYzo6Q29yZTo6Q29tbWl0bWVudDo6VjFiBnByb3RvMw", [file_gogoproto_gogo, file_cosmos_ics23_v1_proofs]);

/**
 * MerkleRoot defines a merkle root hash.
 * In the Cosmos SDK, the AppHash of a block header becomes the root.
 *
 * @generated from message ibc.core.commitment.v1.MerkleRoot
 */
export type MerkleRoot = Message<"ibc.core.commitment.v1.MerkleRoot"> & {
  /**
   * @generated from field: bytes hash = 1;
   */
  hash: Uint8Array;
};

/**
 * Describes the message ibc.core.commitment.v1.MerkleRoot.
 * Use `create(MerkleRootSchema)` to create a new message.
 */
export const MerkleRootSchema: GenMessage<MerkleRoot> = /*@__PURE__*/
  messageDesc(file_ibc_core_commitment_v1_commitment, 0);

/**
 * MerklePrefix is merkle path prefixed to the key.
 * The constructed key from the Path and the key will be append(Path.KeyPath,
 * append(Path.KeyPrefix, key...))
 *
 * @generated from message ibc.core.commitment.v1.MerklePrefix
 */
export type MerklePrefix = Message<"ibc.core.commitment.v1.MerklePrefix"> & {
  /**
   * @generated from field: bytes key_prefix = 1;
   */
  keyPrefix: Uint8Array;
};

/**
 * Describes the message ibc.core.commitment.v1.MerklePrefix.
 * Use `create(MerklePrefixSchema)` to create a new message.
 */
export const MerklePrefixSchema: GenMessage<MerklePrefix> = /*@__PURE__*/
  messageDesc(file_ibc_core_commitment_v1_commitment, 1);

/**
 * MerkleProof is a wrapper type over a chain of CommitmentProofs.
 * It demonstrates membership or non-membership for an element or set of
 * elements, verifiable in conjunction with a known commitment root. Proofs
 * should be succinct.
 * MerkleProofs are ordered from leaf-to-root
 *
 * @generated from message ibc.core.commitment.v1.MerkleProof
 */
export type MerkleProof = Message<"ibc.core.commitment.v1.MerkleProof"> & {
  /**
   * @generated from field: repeated cosmos.ics23.v1.CommitmentProof proofs = 1;
   */
  proofs: CommitmentProof[];
};

/**
 * Describes the message ibc.core.commitment.v1.MerkleProof.
 * Use `create(MerkleProofSchema)` to create a new message.
 */
export const MerkleProofSchema: GenMessage<MerkleProof> = /*@__PURE__*/
  messageDesc(file_ibc_core_commitment_v1_commitment, 2);

