// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts"
// @generated from file cosmos/epochs/v1beta1/query.proto (package cosmos.epochs.v1beta1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { QueryCurrentEpochRequest, QueryCurrentEpochResponse, QueryEpochInfosRequest, QueryEpochInfosResponse } from "./query_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * Query defines the gRPC querier service.
 *
 * @generated from service cosmos.epochs.v1beta1.Query
 */
export const Query = {
  typeName: "cosmos.epochs.v1beta1.Query",
  methods: {
    /**
     * EpochInfos provide running epochInfos
     *
     * @generated from rpc cosmos.epochs.v1beta1.Query.EpochInfos
     */
    epochInfos: {
      name: "EpochInfos",
      I: QueryEpochInfosRequest,
      O: QueryEpochInfosResponse,
      kind: MethodKind.Unary,
    },
    /**
     * CurrentEpoch provide current epoch of specified identifier
     *
     * @generated from rpc cosmos.epochs.v1beta1.Query.CurrentEpoch
     */
    currentEpoch: {
      name: "CurrentEpoch",
      I: QueryCurrentEpochRequest,
      O: QueryCurrentEpochResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

