// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file dysonprotocol/storage/v1/query.proto (package dysonprotocol.storage.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64 } from "@bufbuild/protobuf";
import { Storage } from "./storage_pb.js";
import { PageRequest, PageResponse } from "../../../cosmos/base/query/v1beta1/pagination_pb.js";
import { Params } from "./params_pb.js";

/**
 *
 * QueryStorageGetRequest retrieves a single storage entry with optional field
 * extraction.
 *
 * Owner resolution supports both nameservice names and bech32 addresses.
 * Extract parameter enables GJSON path-based field retrieval from stored JSON
 * data.
 *
 * @generated from message dysonprotocol.storage.v1.QueryStorageGetRequest
 */
export class QueryStorageGetRequest extends Message<QueryStorageGetRequest> {
  /**
   * Owner identifier to look up by; accepts nameservice names (e.g.
   * "alice.dys") or bech32 addresses. Resolution is performed server-side prior
   * to querying the store.
   *
   * @generated from field: string owner = 1;
   */
  owner = "";

  /**
   * Index of the storage entry to retrieve.
   *
   * @generated from field: string index = 2;
   */
  index = "";

  /**
   * Optional GJSON path to extract from the storage entry (e.g., "user.name");
   * max 100 characters.
   *
   * @generated from field: string extract = 3;
   */
  extract = "";

  constructor(data?: PartialMessage<QueryStorageGetRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dysonprotocol.storage.v1.QueryStorageGetRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "owner", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "index", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "extract", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryStorageGetRequest {
    return new QueryStorageGetRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryStorageGetRequest {
    return new QueryStorageGetRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryStorageGetRequest {
    return new QueryStorageGetRequest().fromJsonString(jsonString, options);
  }

  static equals(a: QueryStorageGetRequest | PlainMessage<QueryStorageGetRequest> | undefined, b: QueryStorageGetRequest | PlainMessage<QueryStorageGetRequest> | undefined): boolean {
    return proto3.util.equals(QueryStorageGetRequest, a, b);
  }
}

/**
 *
 * Response containing the retrieved storage entry.
 *
 * @generated from message dysonprotocol.storage.v1.QueryStorageGetResponse
 */
export class QueryStorageGetResponse extends Message<QueryStorageGetResponse> {
  /**
   * The storage entry matching the query; data field contains extracted data if
   * extract path was provided.
   *
   * @generated from field: dysonprotocol.storage.v1.Storage entry = 1;
   */
  entry?: Storage;

  constructor(data?: PartialMessage<QueryStorageGetResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dysonprotocol.storage.v1.QueryStorageGetResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "entry", kind: "message", T: Storage },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryStorageGetResponse {
    return new QueryStorageGetResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryStorageGetResponse {
    return new QueryStorageGetResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryStorageGetResponse {
    return new QueryStorageGetResponse().fromJsonString(jsonString, options);
  }

  static equals(a: QueryStorageGetResponse | PlainMessage<QueryStorageGetResponse> | undefined, b: QueryStorageGetResponse | PlainMessage<QueryStorageGetResponse> | undefined): boolean {
    return proto3.util.equals(QueryStorageGetResponse, a, b);
  }
}

/**
 *
 * QueryStorageListRequest lists storage entries with prefix filtering, GJSON
 * filtering, and extraction.
 *
 * Supports complex queries through index_prefix for efficient range scans,
 * GJSON filter for content-based filtering, and GJSON extract for field-level
 * retrieval. Pagination enables efficient iteration over large result sets.
 *
 * @generated from message dysonprotocol.storage.v1.QueryStorageListRequest
 */
export class QueryStorageListRequest extends Message<QueryStorageListRequest> {
  /**
   * Owner identifier to list under; accepts nameservice names (e.g.
   * "alice.dys") or bech32 addresses. Resolution is performed server-side prior
   * to building the range iterator.
   *
   * @generated from field: string owner = 1;
   */
  owner = "";

  /**
   * Index prefix to filter storage entries by; only entries with indexes
   * starting with this prefix are returned.
   *
   * @generated from field: string index_prefix = 2;
   */
  indexPrefix = "";

  /**
   * Optional GJSON filter to further filter entries; supports comparison
   * operators (==, !=, <, <=, >, >=) and pattern matching (% for like, !% for
   * not like); only matching entries included in results; max 100 chars.
   *
   * @generated from field: string filter = 3;
   */
  filter = "";

  /**
   * Optional GJSON path to extract from each entry (e.g., "user.name" extracts
   * "jeff" from {"user": {"name": "jeff"}}); transforms data field in response;
   * max 100 characters.
   *
   * @generated from field: string extract = 4;
   */
  extract = "";

  /**
   * Pagination parameters for result set navigation; supports offset, limit,
   * and key-based pagination.
   *
   * @generated from field: cosmos.base.query.v1beta1.PageRequest pagination = 5;
   */
  pagination?: PageRequest;

  constructor(data?: PartialMessage<QueryStorageListRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dysonprotocol.storage.v1.QueryStorageListRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "owner", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "index_prefix", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "filter", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "extract", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "pagination", kind: "message", T: PageRequest },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryStorageListRequest {
    return new QueryStorageListRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryStorageListRequest {
    return new QueryStorageListRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryStorageListRequest {
    return new QueryStorageListRequest().fromJsonString(jsonString, options);
  }

  static equals(a: QueryStorageListRequest | PlainMessage<QueryStorageListRequest> | undefined, b: QueryStorageListRequest | PlainMessage<QueryStorageListRequest> | undefined): boolean {
    return proto3.util.equals(QueryStorageListRequest, a, b);
  }
}

/**
 *
 * Response containing list of storage entries matching the query criteria.
 *
 * @generated from message dysonprotocol.storage.v1.QueryStorageListResponse
 */
export class QueryStorageListResponse extends Message<QueryStorageListResponse> {
  /**
   * List of storage entries matching owner, index_prefix, and filter criteria;
   * data may be transformed by extract parameter.
   *
   * @generated from field: repeated dysonprotocol.storage.v1.Storage entries = 1;
   */
  entries: Storage[] = [];

  /**
   * Pagination metadata including next key for continued iteration and total
   * count if requested.
   *
   * @generated from field: cosmos.base.query.v1beta1.PageResponse pagination = 2;
   */
  pagination?: PageResponse;

  constructor(data?: PartialMessage<QueryStorageListResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dysonprotocol.storage.v1.QueryStorageListResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "entries", kind: "message", T: Storage, repeated: true },
    { no: 2, name: "pagination", kind: "message", T: PageResponse },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryStorageListResponse {
    return new QueryStorageListResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryStorageListResponse {
    return new QueryStorageListResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryStorageListResponse {
    return new QueryStorageListResponse().fromJsonString(jsonString, options);
  }

  static equals(a: QueryStorageListResponse | PlainMessage<QueryStorageListResponse> | undefined, b: QueryStorageListResponse | PlainMessage<QueryStorageListResponse> | undefined): boolean {
    return proto3.util.equals(QueryStorageListResponse, a, b);
  }
}

/**
 *
 * Empty request for retrieving current storage module parameters.
 *
 * @generated from message dysonprotocol.storage.v1.QueryParamsRequest
 */
export class QueryParamsRequest extends Message<QueryParamsRequest> {
  constructor(data?: PartialMessage<QueryParamsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dysonprotocol.storage.v1.QueryParamsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryParamsRequest {
    return new QueryParamsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryParamsRequest {
    return new QueryParamsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryParamsRequest {
    return new QueryParamsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: QueryParamsRequest | PlainMessage<QueryParamsRequest> | undefined, b: QueryParamsRequest | PlainMessage<QueryParamsRequest> | undefined): boolean {
    return proto3.util.equals(QueryParamsRequest, a, b);
  }
}

/**
 *
 * Response containing the current storage module parameters.
 *
 * @generated from message dysonprotocol.storage.v1.QueryParamsResponse
 */
export class QueryParamsResponse extends Message<QueryParamsResponse> {
  /**
   * Current module parameters including MaxStorageSize and
   * StorageStakeMultiple.
   *
   * @generated from field: dysonprotocol.storage.v1.Params params = 1;
   */
  params?: Params;

  constructor(data?: PartialMessage<QueryParamsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dysonprotocol.storage.v1.QueryParamsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "params", kind: "message", T: Params },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryParamsResponse {
    return new QueryParamsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryParamsResponse {
    return new QueryParamsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryParamsResponse {
    return new QueryParamsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: QueryParamsResponse | PlainMessage<QueryParamsResponse> | undefined, b: QueryParamsResponse | PlainMessage<QueryParamsResponse> | undefined): boolean {
    return proto3.util.equals(QueryParamsResponse, a, b);
  }
}

/**
 *
 * QueryMetricsRequest retrieves storage usage metrics for an owner.
 *
 * Metrics include total bytes stored, calculated stake requirements, and
 * current stake amount.
 *
 * @generated from message dysonprotocol.storage.v1.QueryMetricsRequest
 */
export class QueryMetricsRequest extends Message<QueryMetricsRequest> {
  /**
   * Owner identifier to query metrics for; accepts nameservice names (resolved
   * to addresses) or bech32 addresses directly. Resolution occurs server-side
   * before computing metrics.
   *
   * @generated from field: string owner = 1;
   */
  owner = "";

  constructor(data?: PartialMessage<QueryMetricsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dysonprotocol.storage.v1.QueryMetricsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "owner", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryMetricsRequest {
    return new QueryMetricsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryMetricsRequest {
    return new QueryMetricsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryMetricsRequest {
    return new QueryMetricsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: QueryMetricsRequest | PlainMessage<QueryMetricsRequest> | undefined, b: QueryMetricsRequest | PlainMessage<QueryMetricsRequest> | undefined): boolean {
    return proto3.util.equals(QueryMetricsRequest, a, b);
  }
}

/**
 *
 * Response containing storage metrics and stake information for an owner.
 *
 * @generated from message dysonprotocol.storage.v1.QueryMetricsResponse
 */
export class QueryMetricsResponse extends Message<QueryMetricsResponse> {
  /**
   * Resolved account address that owns the storage entries.
   *
   * @generated from field: string owner = 1;
   */
  owner = "";

  /**
   * Total number of bytes consumed by all storage entries for this owner.
   *
   * @generated from field: uint64 total_bytes = 2;
   */
  totalBytes = protoInt64.zero;

  /**
   * Minimum stake required in udys for current storage usage (total_bytes ×
   * storage_stake_multiple).
   *
   * @generated from field: string min_stake_amount = 3;
   */
  minStakeAmount = "";

  /**
   * Owner's current total delegated stake in udys across all validators.
   *
   * @generated from field: string current_stake_amount = 4;
   */
  currentStakeAmount = "";

  constructor(data?: PartialMessage<QueryMetricsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dysonprotocol.storage.v1.QueryMetricsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "owner", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "total_bytes", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 3, name: "min_stake_amount", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "current_stake_amount", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryMetricsResponse {
    return new QueryMetricsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryMetricsResponse {
    return new QueryMetricsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryMetricsResponse {
    return new QueryMetricsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: QueryMetricsResponse | PlainMessage<QueryMetricsResponse> | undefined, b: QueryMetricsResponse | PlainMessage<QueryMetricsResponse> | undefined): boolean {
    return proto3.util.equals(QueryMetricsResponse, a, b);
  }
}

