// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file dysonprotocol/storage/v1/storage.proto (package dysonprotocol.storage.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64 } from "@bufbuild/protobuf";

/**
 * @generated from message dysonprotocol.storage.v1.Storage
 */
export class Storage extends Message<Storage> {
  /**
   * owner is the account address that owns this storage entry.
   *
   * @generated from field: string owner = 1;
   */
  owner = "";

  /**
   * index is the key/index for the storage entry (within the owner's
   * namespace).
   *
   * @generated from field: string index = 2;
   */
  index = "";

  /**
   * data is the stored string value associated with the index.
   *
   * @generated from field: string data = 3;
   */
  data = "";

  /**
   * updated_height is block height of last modification.
   *
   * @generated from field: uint64 updated_height = 4;
   */
  updatedHeight = protoInt64.zero;

  /**
   * updated_timestamp is the block time in UTC (RFC3339 e.g.
   * "2025-06-11T15:23:00Z") when entry was modified.
   *
   * @generated from field: string updated_timestamp = 5;
   */
  updatedTimestamp = "";

  /**
   * hash is SHA-256 hex of data field.
   *
   * @generated from field: string hash = 6;
   */
  hash = "";

  constructor(data?: PartialMessage<Storage>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dysonprotocol.storage.v1.Storage";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "owner", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "index", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "data", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "updated_height", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 5, name: "updated_timestamp", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "hash", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Storage {
    return new Storage().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Storage {
    return new Storage().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Storage {
    return new Storage().fromJsonString(jsonString, options);
  }

  static equals(a: Storage | PlainMessage<Storage> | undefined, b: Storage | PlainMessage<Storage> | undefined): boolean {
    return proto3.util.equals(Storage, a, b);
  }
}

/**
 * @generated from message dysonprotocol.storage.v1.StorageMetrics
 */
export class StorageMetrics extends Message<StorageMetrics> {
  /**
   * owner is the account address that owns storage entries.
   *
   * @generated from field: string owner = 1;
   */
  owner = "";

  /**
   * total_bytes is the total number of bytes consumed by all storage entries
   * for this owner address.
   *
   * @generated from field: uint64 total_bytes = 2;
   */
  totalBytes = protoInt64.zero;

  /**
   * min_stake_amount is the minimum stake required in udys for the current
   * storage usage (total_bytes × storage_stake_multiple).
   *
   * @generated from field: string min_stake_amount = 3;
   */
  minStakeAmount = "";

  constructor(data?: PartialMessage<StorageMetrics>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dysonprotocol.storage.v1.StorageMetrics";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "owner", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "total_bytes", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 3, name: "min_stake_amount", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StorageMetrics {
    return new StorageMetrics().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StorageMetrics {
    return new StorageMetrics().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): StorageMetrics {
    return new StorageMetrics().fromJsonString(jsonString, options);
  }

  static equals(a: StorageMetrics | PlainMessage<StorageMetrics> | undefined, b: StorageMetrics | PlainMessage<StorageMetrics> | undefined): boolean {
    return proto3.util.equals(StorageMetrics, a, b);
  }
}

