// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file dysonprotocol/storage/v1/tx.proto (package dysonprotocol.storage.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import { Params } from "./params_pb.js";

/**
 *
 * MsgStorageSet
 *
 * @generated from message dysonprotocol.storage.v1.MsgStorageSet
 */
export class MsgStorageSet extends Message<MsgStorageSet> {
  /**
   * Account address that owns the storage entry; must be a valid bech32
   * address.
   *
   * @generated from field: string owner = 1;
   */
  owner = "";

  /**
   * Index key for the storage entry; must be non-empty and printable ASCII
   * only.
   *
   * @generated from field: string index = 2;
   */
  index = "";

  /**
   * JSON data to store; size limited by MaxStorageSize parameter.
   *
   * @generated from field: string data = 3;
   */
  data = "";

  constructor(data?: PartialMessage<MsgStorageSet>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dysonprotocol.storage.v1.MsgStorageSet";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "owner", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "index", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "data", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgStorageSet {
    return new MsgStorageSet().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgStorageSet {
    return new MsgStorageSet().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgStorageSet {
    return new MsgStorageSet().fromJsonString(jsonString, options);
  }

  static equals(a: MsgStorageSet | PlainMessage<MsgStorageSet> | undefined, b: MsgStorageSet | PlainMessage<MsgStorageSet> | undefined): boolean {
    return proto3.util.equals(MsgStorageSet, a, b);
  }
}

/**
 *
 * Empty response. See EventStorageUpdated for emitted details.
 *
 * @generated from message dysonprotocol.storage.v1.MsgStorageSetResponse
 */
export class MsgStorageSetResponse extends Message<MsgStorageSetResponse> {
  constructor(data?: PartialMessage<MsgStorageSetResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dysonprotocol.storage.v1.MsgStorageSetResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgStorageSetResponse {
    return new MsgStorageSetResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgStorageSetResponse {
    return new MsgStorageSetResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgStorageSetResponse {
    return new MsgStorageSetResponse().fromJsonString(jsonString, options);
  }

  static equals(a: MsgStorageSetResponse | PlainMessage<MsgStorageSetResponse> | undefined, b: MsgStorageSetResponse | PlainMessage<MsgStorageSetResponse> | undefined): boolean {
    return proto3.util.equals(MsgStorageSetResponse, a, b);
  }
}

/**
 *
 * MsgStorageDelete is the message for deleting storage entries.
 *
 * Behavior:
 * - Deletes multiple storage entries by index for the specified owner.
 * - Verifies ownership of each entry before deletion to prevent unauthorized
 * removal.
 * - Updates owner's storage metrics by subtracting deleted bytes from total.
 * - Returns list of successfully deleted indexes for transparency.
 *
 * Validation:
 * - Owner must be a valid bech32 address.
 * - At least one index must be specified for deletion.
 * - Each specified index must exist and be owned by the requesting account.
 *
 * Emits:
 * - EventStorageDelete(owner, deleted_indexes) with list of successfully
 * deleted indexes.
 *
 * Returns:
 * - List of indexes that were successfully deleted.
 *
 * @generated from message dysonprotocol.storage.v1.MsgStorageDelete
 */
export class MsgStorageDelete extends Message<MsgStorageDelete> {
  /**
   * Account address that owns the storage entries; must be a valid bech32
   * address.
   *
   * @generated from field: string owner = 1;
   */
  owner = "";

  /**
   * List of specific indexes to delete; must contain at least one index.
   *
   * @generated from field: repeated string indexes = 2;
   */
  indexes: string[] = [];

  constructor(data?: PartialMessage<MsgStorageDelete>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dysonprotocol.storage.v1.MsgStorageDelete";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "owner", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "indexes", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgStorageDelete {
    return new MsgStorageDelete().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgStorageDelete {
    return new MsgStorageDelete().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgStorageDelete {
    return new MsgStorageDelete().fromJsonString(jsonString, options);
  }

  static equals(a: MsgStorageDelete | PlainMessage<MsgStorageDelete> | undefined, b: MsgStorageDelete | PlainMessage<MsgStorageDelete> | undefined): boolean {
    return proto3.util.equals(MsgStorageDelete, a, b);
  }
}

/**
 *
 * Response containing the list of indexes that were successfully deleted.
 *
 * @generated from message dysonprotocol.storage.v1.MsgStorageDeleteResponse
 */
export class MsgStorageDeleteResponse extends Message<MsgStorageDeleteResponse> {
  /**
   * List of indexes that were successfully deleted; may be fewer than requested
   * if some didn't exist.
   *
   * @generated from field: repeated string deleted_indexes = 1;
   */
  deletedIndexes: string[] = [];

  constructor(data?: PartialMessage<MsgStorageDeleteResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dysonprotocol.storage.v1.MsgStorageDeleteResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "deleted_indexes", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgStorageDeleteResponse {
    return new MsgStorageDeleteResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgStorageDeleteResponse {
    return new MsgStorageDeleteResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgStorageDeleteResponse {
    return new MsgStorageDeleteResponse().fromJsonString(jsonString, options);
  }

  static equals(a: MsgStorageDeleteResponse | PlainMessage<MsgStorageDeleteResponse> | undefined, b: MsgStorageDeleteResponse | PlainMessage<MsgStorageDeleteResponse> | undefined): boolean {
    return proto3.util.equals(MsgStorageDeleteResponse, a, b);
  }
}

/**
 *
 * MsgUpdateParams is the Msg/UpdateParams request type.
 *
 * Behavior:
 * - Validates that the signer has authority to update module parameters
 * (typically governance module).
 * - Validates that all provided parameters are valid according to parameter
 * constraints.
 * - Updates the module's parameter state with the new values.
 *
 * Validation:
 * - Authority must match the module's configured authority address.
 * - All parameter values must pass individual validation (MaxStorageSize,
 * StorageStakeMultiple).
 *
 * Emits:
 * - No events emitted for parameter updates.
 *
 * Returns:
 * - Empty response body on success.
 *
 * @generated from message dysonprotocol.storage.v1.MsgUpdateParams
 */
export class MsgUpdateParams extends Message<MsgUpdateParams> {
  /**
   * Authority is the address that controls the module (defaults to x/gov unless
   * overwritten).
   *
   * @generated from field: string authority = 1;
   */
  authority = "";

  /**
   * Params defines the x/storage parameters to update; all parameters must be
   * supplied.
   *
   * @generated from field: dysonprotocol.storage.v1.Params params = 2;
   */
  params?: Params;

  constructor(data?: PartialMessage<MsgUpdateParams>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dysonprotocol.storage.v1.MsgUpdateParams";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "authority", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "params", kind: "message", T: Params },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgUpdateParams {
    return new MsgUpdateParams().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgUpdateParams {
    return new MsgUpdateParams().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgUpdateParams {
    return new MsgUpdateParams().fromJsonString(jsonString, options);
  }

  static equals(a: MsgUpdateParams | PlainMessage<MsgUpdateParams> | undefined, b: MsgUpdateParams | PlainMessage<MsgUpdateParams> | undefined): boolean {
    return proto3.util.equals(MsgUpdateParams, a, b);
  }
}

/**
 *
 * Empty response. Parameter updates do not emit events.
 *
 * @generated from message dysonprotocol.storage.v1.MsgUpdateParamsResponse
 */
export class MsgUpdateParamsResponse extends Message<MsgUpdateParamsResponse> {
  constructor(data?: PartialMessage<MsgUpdateParamsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dysonprotocol.storage.v1.MsgUpdateParamsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgUpdateParamsResponse {
    return new MsgUpdateParamsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgUpdateParamsResponse {
    return new MsgUpdateParamsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgUpdateParamsResponse {
    return new MsgUpdateParamsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: MsgUpdateParamsResponse | PlainMessage<MsgUpdateParamsResponse> | undefined, b: MsgUpdateParamsResponse | PlainMessage<MsgUpdateParamsResponse> | undefined): boolean {
    return proto3.util.equals(MsgUpdateParamsResponse, a, b);
  }
}

