// @generated by protoc-gen-es v2.9.0 with parameter "target=ts"
// @generated from file ibc/applications/interchain_accounts/host/v1/query.proto (package ibc.applications.interchain_accounts.host.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../../../../../google/api/annotations_pb";
import type { Params } from "./host_pb";
import { file_ibc_applications_interchain_accounts_host_v1_host } from "./host_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file ibc/applications/interchain_accounts/host/v1/query.proto.
 */
export const file_ibc_applications_interchain_accounts_host_v1_query: GenFile = /*@__PURE__*/
  fileDesc("CjhpYmMvYXBwbGljYXRpb25zL2ludGVyY2hhaW5fYWNjb3VudHMvaG9zdC92MS9xdWVyeS5wcm90bxIsaWJjLmFwcGxpY2F0aW9ucy5pbnRlcmNoYWluX2FjY291bnRzLmhvc3QudjEiFAoSUXVlcnlQYXJhbXNSZXF1ZXN0IlsKE1F1ZXJ5UGFyYW1zUmVzcG9uc2USRAoGcGFyYW1zGAEgASgLMjQuaWJjLmFwcGxpY2F0aW9ucy5pbnRlcmNoYWluX2FjY291bnRzLmhvc3QudjEuUGFyYW1zMs0BCgVRdWVyeRLDAQoGUGFyYW1zEkAuaWJjLmFwcGxpY2F0aW9ucy5pbnRlcmNoYWluX2FjY291bnRzLmhvc3QudjEuUXVlcnlQYXJhbXNSZXF1ZXN0GkEuaWJjLmFwcGxpY2F0aW9ucy5pbnRlcmNoYWluX2FjY291bnRzLmhvc3QudjEuUXVlcnlQYXJhbXNSZXNwb25zZSI0gtPkkwIuEiwvaWJjL2FwcHMvaW50ZXJjaGFpbl9hY2NvdW50cy9ob3N0L3YxL3BhcmFtc0JNWktnaXRodWIuY29tL2Nvc21vcy9pYmMtZ28vdjEwL21vZHVsZXMvYXBwcy8yNy1pbnRlcmNoYWluLWFjY291bnRzL2hvc3QvdHlwZXNiBnByb3RvMw", [file_google_api_annotations, file_ibc_applications_interchain_accounts_host_v1_host]);

/**
 * QueryParamsRequest is the request type for the Query/Params RPC method.
 *
 * @generated from message ibc.applications.interchain_accounts.host.v1.QueryParamsRequest
 */
export type QueryParamsRequest = Message<"ibc.applications.interchain_accounts.host.v1.QueryParamsRequest"> & {
};

/**
 * Describes the message ibc.applications.interchain_accounts.host.v1.QueryParamsRequest.
 * Use `create(QueryParamsRequestSchema)` to create a new message.
 */
export const QueryParamsRequestSchema: GenMessage<QueryParamsRequest> = /*@__PURE__*/
  messageDesc(file_ibc_applications_interchain_accounts_host_v1_query, 0);

/**
 * QueryParamsResponse is the response type for the Query/Params RPC method.
 *
 * @generated from message ibc.applications.interchain_accounts.host.v1.QueryParamsResponse
 */
export type QueryParamsResponse = Message<"ibc.applications.interchain_accounts.host.v1.QueryParamsResponse"> & {
  /**
   * params defines the parameters of the module.
   *
   * @generated from field: ibc.applications.interchain_accounts.host.v1.Params params = 1;
   */
  params?: Params;
};

/**
 * Describes the message ibc.applications.interchain_accounts.host.v1.QueryParamsResponse.
 * Use `create(QueryParamsResponseSchema)` to create a new message.
 */
export const QueryParamsResponseSchema: GenMessage<QueryParamsResponse> = /*@__PURE__*/
  messageDesc(file_ibc_applications_interchain_accounts_host_v1_query, 1);

/**
 * Query provides defines the gRPC querier service.
 *
 * @generated from service ibc.applications.interchain_accounts.host.v1.Query
 */
export const Query: GenService<{
  /**
   * Params queries all parameters of the ICA host submodule.
   *
   * @generated from rpc ibc.applications.interchain_accounts.host.v1.Query.Params
   */
  params: {
    methodKind: "unary";
    input: typeof QueryParamsRequestSchema;
    output: typeof QueryParamsResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_ibc_applications_interchain_accounts_host_v1_query, 0);

