// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file dysonprotocol/crontask/v1/events.proto (package dysonprotocol.crontask.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64 } from "@bufbuild/protobuf";
import { Coin } from "../../../cosmos/base/v1beta1/coin_pb.js";

/**
 * EventTaskCreated is emitted when a new task is created
 *
 * @generated from message dysonprotocol.crontask.v1.EventTaskCreated
 */
export class EventTaskCreated extends Message<EventTaskCreated> {
  /**
   * @generated from field: uint64 task_id = 1;
   */
  taskId = protoInt64.zero;

  /**
   * @generated from field: string creator = 2;
   */
  creator = "";

  constructor(data?: PartialMessage<EventTaskCreated>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dysonprotocol.crontask.v1.EventTaskCreated";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "task_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 2, name: "creator", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): EventTaskCreated {
    return new EventTaskCreated().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): EventTaskCreated {
    return new EventTaskCreated().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): EventTaskCreated {
    return new EventTaskCreated().fromJsonString(jsonString, options);
  }

  static equals(a: EventTaskCreated | PlainMessage<EventTaskCreated> | undefined, b: EventTaskCreated | PlainMessage<EventTaskCreated> | undefined): boolean {
    return proto3.util.equals(EventTaskCreated, a, b);
  }
}

/**
 * EventTaskPending is emitted when a task transitions to PENDING
 *
 * @generated from message dysonprotocol.crontask.v1.EventTaskPending
 */
export class EventTaskPending extends Message<EventTaskPending> {
  /**
   * @generated from field: uint64 task_id = 1;
   */
  taskId = protoInt64.zero;

  /**
   * @generated from field: string creator = 2;
   */
  creator = "";

  constructor(data?: PartialMessage<EventTaskPending>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dysonprotocol.crontask.v1.EventTaskPending";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "task_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 2, name: "creator", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): EventTaskPending {
    return new EventTaskPending().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): EventTaskPending {
    return new EventTaskPending().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): EventTaskPending {
    return new EventTaskPending().fromJsonString(jsonString, options);
  }

  static equals(a: EventTaskPending | PlainMessage<EventTaskPending> | undefined, b: EventTaskPending | PlainMessage<EventTaskPending> | undefined): boolean {
    return proto3.util.equals(EventTaskPending, a, b);
  }
}

/**
 * EventTaskDeleted is emitted when a task is deleted
 *
 * @generated from message dysonprotocol.crontask.v1.EventTaskDeleted
 */
export class EventTaskDeleted extends Message<EventTaskDeleted> {
  /**
   * @generated from field: uint64 task_id = 1;
   */
  taskId = protoInt64.zero;

  /**
   * @generated from field: string creator = 2;
   */
  creator = "";

  constructor(data?: PartialMessage<EventTaskDeleted>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dysonprotocol.crontask.v1.EventTaskDeleted";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "task_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 2, name: "creator", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): EventTaskDeleted {
    return new EventTaskDeleted().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): EventTaskDeleted {
    return new EventTaskDeleted().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): EventTaskDeleted {
    return new EventTaskDeleted().fromJsonString(jsonString, options);
  }

  static equals(a: EventTaskDeleted | PlainMessage<EventTaskDeleted> | undefined, b: EventTaskDeleted | PlainMessage<EventTaskDeleted> | undefined): boolean {
    return proto3.util.equals(EventTaskDeleted, a, b);
  }
}

/**
 * EventTaskExecuted is emitted when a task is executed
 *
 * @generated from message dysonprotocol.crontask.v1.EventTaskExecuted
 */
export class EventTaskExecuted extends Message<EventTaskExecuted> {
  /**
   * @generated from field: uint64 task_id = 1;
   */
  taskId = protoInt64.zero;

  /**
   * @generated from field: string creator = 2;
   */
  creator = "";

  /**
   * @generated from field: string status = 3;
   */
  status = "";

  /**
   * @generated from field: bool success = 4;
   */
  success = false;

  constructor(data?: PartialMessage<EventTaskExecuted>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dysonprotocol.crontask.v1.EventTaskExecuted";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "task_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 2, name: "creator", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "success", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): EventTaskExecuted {
    return new EventTaskExecuted().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): EventTaskExecuted {
    return new EventTaskExecuted().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): EventTaskExecuted {
    return new EventTaskExecuted().fromJsonString(jsonString, options);
  }

  static equals(a: EventTaskExecuted | PlainMessage<EventTaskExecuted> | undefined, b: EventTaskExecuted | PlainMessage<EventTaskExecuted> | undefined): boolean {
    return proto3.util.equals(EventTaskExecuted, a, b);
  }
}

/**
 * EventTaskExpired is emitted when a task expires without being executed
 *
 * @generated from message dysonprotocol.crontask.v1.EventTaskExpired
 */
export class EventTaskExpired extends Message<EventTaskExpired> {
  /**
   * @generated from field: uint64 task_id = 1;
   */
  taskId = protoInt64.zero;

  /**
   * @generated from field: string creator = 2;
   */
  creator = "";

  constructor(data?: PartialMessage<EventTaskExpired>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dysonprotocol.crontask.v1.EventTaskExpired";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "task_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 2, name: "creator", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): EventTaskExpired {
    return new EventTaskExpired().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): EventTaskExpired {
    return new EventTaskExpired().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): EventTaskExpired {
    return new EventTaskExpired().fromJsonString(jsonString, options);
  }

  static equals(a: EventTaskExpired | PlainMessage<EventTaskExpired> | undefined, b: EventTaskExpired | PlainMessage<EventTaskExpired> | undefined): boolean {
    return proto3.util.equals(EventTaskExpired, a, b);
  }
}

/**
 * EventTaskFailed is emitted when a task finishes with failure
 *
 * @generated from message dysonprotocol.crontask.v1.EventTaskFailed
 */
export class EventTaskFailed extends Message<EventTaskFailed> {
  /**
   * @generated from field: uint64 task_id = 1;
   */
  taskId = protoInt64.zero;

  /**
   * @generated from field: string creator = 2;
   */
  creator = "";

  /**
   * @generated from field: string error = 3;
   */
  error = "";

  constructor(data?: PartialMessage<EventTaskFailed>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dysonprotocol.crontask.v1.EventTaskFailed";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "task_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 2, name: "creator", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "error", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): EventTaskFailed {
    return new EventTaskFailed().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): EventTaskFailed {
    return new EventTaskFailed().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): EventTaskFailed {
    return new EventTaskFailed().fromJsonString(jsonString, options);
  }

  static equals(a: EventTaskFailed | PlainMessage<EventTaskFailed> | undefined, b: EventTaskFailed | PlainMessage<EventTaskFailed> | undefined): boolean {
    return proto3.util.equals(EventTaskFailed, a, b);
  }
}

/**
 * EventTaskPurged is emitted when a terminal task is removed by retention
 * cleanup
 *
 * @generated from message dysonprotocol.crontask.v1.EventTaskPurged
 */
export class EventTaskPurged extends Message<EventTaskPurged> {
  /**
   * @generated from field: uint64 task_id = 1;
   */
  taskId = protoInt64.zero;

  /**
   * @generated from field: string status = 2;
   */
  status = "";

  /**
   * @generated from field: string creator = 3;
   */
  creator = "";

  constructor(data?: PartialMessage<EventTaskPurged>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dysonprotocol.crontask.v1.EventTaskPurged";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "task_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 2, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "creator", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): EventTaskPurged {
    return new EventTaskPurged().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): EventTaskPurged {
    return new EventTaskPurged().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): EventTaskPurged {
    return new EventTaskPurged().fromJsonString(jsonString, options);
  }

  static equals(a: EventTaskPurged | PlainMessage<EventTaskPurged> | undefined, b: EventTaskPurged | PlainMessage<EventTaskPurged> | undefined): boolean {
    return proto3.util.equals(EventTaskPurged, a, b);
  }
}

/**
 * EventCrontaskMetrics is emitted once per block with last-block metrics
 * snapshot
 *
 * @generated from message dysonprotocol.crontask.v1.EventCrontaskMetrics
 */
export class EventCrontaskMetrics extends Message<EventCrontaskMetrics> {
  /**
   * executed totals
   *
   * @generated from field: uint64 executed_total_gas = 1;
   */
  executedTotalGas = protoInt64.zero;

  /**
   * @generated from field: repeated cosmos.base.v1beta1.Coin executed_total_fees = 2;
   */
  executedTotalFees: Coin[] = [];

  /**
   * @generated from field: uint64 executed_task_count = 3;
   */
  executedTaskCount = protoInt64.zero;

  /**
   * pending snapshot at BeginBlock
   *
   * @generated from field: uint64 pending_task_count = 10;
   */
  pendingTaskCount = protoInt64.zero;

  /**
   * @generated from field: uint64 pending_gas_requested = 11;
   */
  pendingGasRequested = protoInt64.zero;

  /**
   * @generated from field: int64 pending_oldest_scheduled_ts = 12;
   */
  pendingOldestScheduledTs = protoInt64.zero;

  /**
   * sum of task_gas_fee across all PENDING tasks at BeginBlock
   *
   * @generated from field: repeated cosmos.base.v1beta1.Coin pending_total_gas_fees = 13;
   */
  pendingTotalGasFees: Coin[] = [];

  constructor(data?: PartialMessage<EventCrontaskMetrics>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dysonprotocol.crontask.v1.EventCrontaskMetrics";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "executed_total_gas", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 2, name: "executed_total_fees", kind: "message", T: Coin, repeated: true },
    { no: 3, name: "executed_task_count", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 10, name: "pending_task_count", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 11, name: "pending_gas_requested", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 12, name: "pending_oldest_scheduled_ts", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 13, name: "pending_total_gas_fees", kind: "message", T: Coin, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): EventCrontaskMetrics {
    return new EventCrontaskMetrics().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): EventCrontaskMetrics {
    return new EventCrontaskMetrics().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): EventCrontaskMetrics {
    return new EventCrontaskMetrics().fromJsonString(jsonString, options);
  }

  static equals(a: EventCrontaskMetrics | PlainMessage<EventCrontaskMetrics> | undefined, b: EventCrontaskMetrics | PlainMessage<EventCrontaskMetrics> | undefined): boolean {
    return proto3.util.equals(EventCrontaskMetrics, a, b);
  }
}

/**
 * Emitted when a new event subscription is created
 *
 * @generated from message dysonprotocol.crontask.v1.EventSubscriptionCreated
 */
export class EventSubscriptionCreated extends Message<EventSubscriptionCreated> {
  /**
   * @generated from field: uint64 subscription_id = 1;
   */
  subscriptionId = protoInt64.zero;

  /**
   * @generated from field: string creator = 2;
   */
  creator = "";

  constructor(data?: PartialMessage<EventSubscriptionCreated>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dysonprotocol.crontask.v1.EventSubscriptionCreated";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "subscription_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 2, name: "creator", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): EventSubscriptionCreated {
    return new EventSubscriptionCreated().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): EventSubscriptionCreated {
    return new EventSubscriptionCreated().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): EventSubscriptionCreated {
    return new EventSubscriptionCreated().fromJsonString(jsonString, options);
  }

  static equals(a: EventSubscriptionCreated | PlainMessage<EventSubscriptionCreated> | undefined, b: EventSubscriptionCreated | PlainMessage<EventSubscriptionCreated> | undefined): boolean {
    return proto3.util.equals(EventSubscriptionCreated, a, b);
  }
}

/**
 * Emitted when an event subscription is deleted
 *
 * @generated from message dysonprotocol.crontask.v1.EventSubscriptionDeleted
 */
export class EventSubscriptionDeleted extends Message<EventSubscriptionDeleted> {
  /**
   * @generated from field: uint64 subscription_id = 1;
   */
  subscriptionId = protoInt64.zero;

  /**
   * @generated from field: string creator = 2;
   */
  creator = "";

  constructor(data?: PartialMessage<EventSubscriptionDeleted>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dysonprotocol.crontask.v1.EventSubscriptionDeleted";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "subscription_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 2, name: "creator", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): EventSubscriptionDeleted {
    return new EventSubscriptionDeleted().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): EventSubscriptionDeleted {
    return new EventSubscriptionDeleted().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): EventSubscriptionDeleted {
    return new EventSubscriptionDeleted().fromJsonString(jsonString, options);
  }

  static equals(a: EventSubscriptionDeleted | PlainMessage<EventSubscriptionDeleted> | undefined, b: EventSubscriptionDeleted | PlainMessage<EventSubscriptionDeleted> | undefined): boolean {
    return proto3.util.equals(EventSubscriptionDeleted, a, b);
  }
}

/**
 * Emitted when a subscription is triggered for an event
 *
 * @generated from message dysonprotocol.crontask.v1.EventSubscriptionTriggered
 */
export class EventSubscriptionTriggered extends Message<EventSubscriptionTriggered> {
  /**
   * @generated from field: uint64 subscription_id = 1;
   */
  subscriptionId = protoInt64.zero;

  /**
   * @generated from field: string creator = 2;
   */
  creator = "";

  constructor(data?: PartialMessage<EventSubscriptionTriggered>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dysonprotocol.crontask.v1.EventSubscriptionTriggered";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "subscription_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 2, name: "creator", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): EventSubscriptionTriggered {
    return new EventSubscriptionTriggered().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): EventSubscriptionTriggered {
    return new EventSubscriptionTriggered().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): EventSubscriptionTriggered {
    return new EventSubscriptionTriggered().fromJsonString(jsonString, options);
  }

  static equals(a: EventSubscriptionTriggered | PlainMessage<EventSubscriptionTriggered> | undefined, b: EventSubscriptionTriggered | PlainMessage<EventSubscriptionTriggered> | undefined): boolean {
    return proto3.util.equals(EventSubscriptionTriggered, a, b);
  }
}

