// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts"
// @generated from file dysonprotocol/crontask/v1/tx.proto (package dysonprotocol.crontask.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { MsgCreateSubscription, MsgCreateSubscriptionResponse, MsgCreateTask, MsgCreateTaskResponse, MsgDeleteSubscription, MsgDeleteSubscriptionResponse, MsgDeleteTask, MsgDeleteTaskResponse, MsgRenewSubscription, MsgRenewSubscriptionResponse, MsgUpdateParams, MsgUpdateParamsResponse } from "./tx_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * Msg defines the crontask Msg service
 *
 * @generated from service dysonprotocol.crontask.v1.Msg
 */
export const Msg = {
  typeName: "dysonprotocol.crontask.v1.Msg",
  methods: {
    /**
     *
     * CreateTask creates a new scheduled task with specified execution time and
     * messages.
     *
     * Behavior:
     * - Creates a task scheduled for execution at a future timestamp.
     * - Parses flexible timestamp formats (Unix timestamps or duration offsets
     * like
     * "+1h30m").
     * - Validates scheduling constraints and gas limits against module
     * parameters.
     * - Calculates gas price from fee and limit, stores task with unpacked
     * messages.
     * - Tasks remain in SCHEDULED status until execution time.
     *
     * Validation:
     * - Creator address must be valid.
     * - Scheduled timestamp must be in the future and within MaxScheduledTime
     * limit.
     * - Expiry timestamp must be after scheduled time (defaults to scheduled +
     * ExpiryLimit if not provided).
     * - Gas limit must be positive and not exceed BlockGasLimit.
     * - Gas fee must be positive and denominated in "udys".
     * - At least one message must be provided in the task.
     *
     * Emits:
     * - EventTaskCreated(task_id, creator) on successful task creation.
     *
     * Returns:
     * - MsgCreateTaskResponse with allocated task ID.
     *
     * @generated from rpc dysonprotocol.crontask.v1.Msg.CreateTask
     */
    createTask: {
      name: "CreateTask",
      I: MsgCreateTask,
      O: MsgCreateTaskResponse,
      kind: MethodKind.Unary,
    },
    /**
     *
     * DeleteTask permanently removes a scheduled task.
     *
     * Behavior:
     * - Permanently removes a task from storage before execution.
     * - Only the creator of the task can delete it.
     * - No refunds are provided for task fees or gas.
     *
     * Validation:
     * - Task must exist with the provided ID.
     * - Creator must match the task's creator field.
     *
     * Emits:
     * - EventTaskDeleted(task_id, creator) on successful deletion.
     *
     * Returns:
     * - Empty MsgDeleteTaskResponse.
     *
     * @generated from rpc dysonprotocol.crontask.v1.Msg.DeleteTask
     */
    deleteTask: {
      name: "DeleteTask",
      I: MsgDeleteTask,
      O: MsgDeleteTaskResponse,
      kind: MethodKind.Unary,
    },
    /**
     *
     * UpdateParams updates the parameters of the x/crontask module via
     * governance proposal.
     *
     * Behavior:
     * - Updates all module parameters in a single governance operation.
     * - Authority is typically the x/gov module account.
     * - Parameters control task scheduling limits, gas constraints, and
     * subscription rules.
     *
     * Validation:
     * - Authority must be valid (typically x/gov module account).
     * - All parameter values must pass individual validation (Validate method).
     *
     * Emits:
     * - No events are emitted for parameter updates.
     *
     * Returns:
     * - Empty MsgUpdateParamsResponse.
     *
     * @generated from rpc dysonprotocol.crontask.v1.Msg.UpdateParams
     */
    updateParams: {
      name: "UpdateParams",
      I: MsgUpdateParams,
      O: MsgUpdateParamsResponse,
      kind: MethodKind.Unary,
    },
    /**
     *
     * CreateSubscription creates a new event-triggered subscription with upfront
     * fee payment.
     *
     * Behavior:
     * - Creates a subscription that triggers script execution when events match
     * the filter.
     * - Enforces minimum stake requirements across all creator's subscriptions.
     * - Deducts anti-spam fee to fee_collector module account.
     * - Allocates unique subscription ID and sets expiry to current time +
     * max_subscription_duration.
     * - Minifies JSON args/kwargs for storage efficiency.
     * - Initializes subscription with "enabled" status and zero trigger count.
     *
     * Validation:
     * - Creator address must be valid.
     * - Script address must be valid and non-empty.
     * - Function name must be non-empty.
     * - Task gas limit must be positive.
     * - Task gas fee must be positive.
     * - Filter, script_address, function, args, kwargs must not exceed length
     * limits.
     * - Creator must have sufficient bonded stake if MinStakePerSubscription is
     * configured.
     * - Args/kwargs must be valid JSON (array for args, object for kwargs).
     *
     * Emits:
     * - EventSubscriptionCreated(subscription_id, creator) on successful
     * creation.
     *
     * Returns:
     * - MsgCreateSubscriptionResponse with allocated subscription ID.
     *
     * @generated from rpc dysonprotocol.crontask.v1.Msg.CreateSubscription
     */
    createSubscription: {
      name: "CreateSubscription",
      I: MsgCreateSubscription,
      O: MsgCreateSubscriptionResponse,
      kind: MethodKind.Unary,
    },
    /**
     *
     * DeleteSubscription permanently removes an existing subscription.
     *
     * Behavior:
     * - Permanently removes a subscription from storage.
     * - Only the creator of the subscription can delete it.
     * - No refunds are provided for remaining subscription time or fees.
     *
     * Validation:
     * - Creator address must be valid.
     * - Subscription must exist.
     * - Creator must match the subscription's creator field.
     *
     * Emits:
     * - EventSubscriptionDeleted(subscription_id, creator) on successful
     * deletion.
     *
     * Returns:
     * - Empty MsgDeleteSubscriptionResponse.
     *
     * @generated from rpc dysonprotocol.crontask.v1.Msg.DeleteSubscription
     */
    deleteSubscription: {
      name: "DeleteSubscription",
      I: MsgDeleteSubscription,
      O: MsgDeleteSubscriptionResponse,
      kind: MethodKind.Unary,
    },
    /**
     *
     * RenewSubscription extends subscription expiry and recharges the fee.
     *
     * Behavior:
     * - Extends subscription expiry to current time + max_subscription_duration.
     * - Recharges the task gas fee from creator to fee_collector.
     * - Re-enables "disabled" subscriptions (time-expired or insufficient funds).
     * - Does NOT re-enable "error" subscriptions (unrecoverable issues).
     * - Enforces minimum stake requirements before renewal.
     *
     * Validation:
     * - Creator address must be valid.
     * - Subscription must exist.
     * - Creator must match the subscription's creator field.
     * - Creator must have sufficient bonded stake if MinStakePerSubscription is
     * configured.
     *
     * Emits:
     * - No events are emitted for renewal (subscription remains active).
     *
     * Returns:
     * - Empty MsgRenewSubscriptionResponse.
     *
     * @generated from rpc dysonprotocol.crontask.v1.Msg.RenewSubscription
     */
    renewSubscription: {
      name: "RenewSubscription",
      I: MsgRenewSubscription,
      O: MsgRenewSubscriptionResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

