// @generated by protoc-gen-es v2.9.0 with parameter "target=ts"
// @generated from file cosmos/counter/v1/query.proto (package cosmos.counter.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file cosmos/counter/v1/query.proto.
 */
export const file_cosmos_counter_v1_query: GenFile = /*@__PURE__*/
  fileDesc("Ch1jb3Ntb3MvY291bnRlci92MS9xdWVyeS5wcm90bxIRY29zbW9zLmNvdW50ZXIudjEiFgoUUXVlcnlHZXRDb3VudFJlcXVlc3QiLAoVUXVlcnlHZXRDb3VudFJlc3BvbnNlEhMKC3RvdGFsX2NvdW50GAEgASgDMmYKBVF1ZXJ5El0KCEdldENvdW50EicuY29zbW9zLmNvdW50ZXIudjEuUXVlcnlHZXRDb3VudFJlcXVlc3QaKC5jb3Ntb3MuY291bnRlci52MS5RdWVyeUdldENvdW50UmVzcG9uc2VCN1o1Z2l0aHViLmNvbS9jb3Ntb3MvY29zbW9zLXNkay90ZXN0dXRpbC94L2NvdW50ZXIvdHlwZXNiBnByb3RvMw");

/**
 * QueryGetCountRequest defines the request type for querying x/mock count.
 *
 * @generated from message cosmos.counter.v1.QueryGetCountRequest
 */
export type QueryGetCountRequest = Message<"cosmos.counter.v1.QueryGetCountRequest"> & {
};

/**
 * Describes the message cosmos.counter.v1.QueryGetCountRequest.
 * Use `create(QueryGetCountRequestSchema)` to create a new message.
 */
export const QueryGetCountRequestSchema: GenMessage<QueryGetCountRequest> = /*@__PURE__*/
  messageDesc(file_cosmos_counter_v1_query, 0);

/**
 * QueryGetCountResponse defines the response type for querying x/mock count.
 *
 * @generated from message cosmos.counter.v1.QueryGetCountResponse
 */
export type QueryGetCountResponse = Message<"cosmos.counter.v1.QueryGetCountResponse"> & {
  /**
   * @generated from field: int64 total_count = 1;
   */
  totalCount: bigint;
};

/**
 * Describes the message cosmos.counter.v1.QueryGetCountResponse.
 * Use `create(QueryGetCountResponseSchema)` to create a new message.
 */
export const QueryGetCountResponseSchema: GenMessage<QueryGetCountResponse> = /*@__PURE__*/
  messageDesc(file_cosmos_counter_v1_query, 1);

/**
 * Query defines the gRPC querier service.
 *
 * @generated from service cosmos.counter.v1.Query
 */
export const Query: GenService<{
  /**
   * GetCount queries the parameters of x/Counter module.
   *
   * @generated from rpc cosmos.counter.v1.Query.GetCount
   */
  getCount: {
    methodKind: "unary";
    input: typeof QueryGetCountRequestSchema;
    output: typeof QueryGetCountResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_cosmos_counter_v1_query, 0);

