// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts"
// @generated from file cosmos/counter/v1/tx.proto (package cosmos.counter.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { MsgIncreaseCounter, MsgIncreaseCountResponse } from "./tx_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * Msg defines the counter Msg service.
 *
 * @generated from service cosmos.counter.v1.Msg
 */
export const Msg = {
  typeName: "cosmos.counter.v1.Msg",
  methods: {
    /**
     * IncreaseCount increments the counter by the specified amount.
     *
     * @generated from rpc cosmos.counter.v1.Msg.IncreaseCount
     */
    increaseCount: {
      name: "IncreaseCount",
      I: MsgIncreaseCounter,
      O: MsgIncreaseCountResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

