// @generated by protoc-gen-es v2.9.0 with parameter "target=ts"
// @generated from file ibc/applications/transfer/v1/genesis.proto (package ibc.applications.transfer.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Params } from "./transfer_pb";
import { file_ibc_applications_transfer_v1_transfer } from "./transfer_pb";
import type { Denom } from "./token_pb";
import { file_ibc_applications_transfer_v1_token } from "./token_pb";
import type { Coin } from "../../../../cosmos/base/v1beta1/coin_pb";
import { file_cosmos_base_v1beta1_coin } from "../../../../cosmos/base/v1beta1/coin_pb";
import { file_gogoproto_gogo } from "../../../../gogoproto/gogo_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file ibc/applications/transfer/v1/genesis.proto.
 */
export const file_ibc_applications_transfer_v1_genesis: GenFile = /*@__PURE__*/
  fileDesc("CippYmMvYXBwbGljYXRpb25zL3RyYW5zZmVyL3YxL2dlbmVzaXMucHJvdG8SHGliYy5hcHBsaWNhdGlvbnMudHJhbnNmZXIudjEihQIKDEdlbmVzaXNTdGF0ZRIPCgdwb3J0X2lkGAEgASgJEkMKBmRlbm9tcxgCIAMoCzIjLmliYy5hcHBsaWNhdGlvbnMudHJhbnNmZXIudjEuRGVub21CDsjeHwCq3x8GRGVub21zEjoKBnBhcmFtcxgDIAEoCzIkLmliYy5hcHBsaWNhdGlvbnMudHJhbnNmZXIudjEuUGFyYW1zQgTI3h8AEmMKDnRvdGFsX2VzY3Jvd2VkGAQgAygLMhkuY29zbW9zLmJhc2UudjFiZXRhMS5Db2luQjDI3h8Aqt8fKGdpdGh1Yi5jb20vY29zbW9zL2Nvc21vcy1zZGsvdHlwZXMuQ29pbnNC/QEKIGNvbS5pYmMuYXBwbGljYXRpb25zLnRyYW5zZmVyLnYxQgxHZW5lc2lzUHJvdG9QAVo4Z2l0aHViLmNvbS9jb3Ntb3MvaWJjLWdvL3YxMC9tb2R1bGVzL2FwcHMvdHJhbnNmZXIvdHlwZXOiAgNJQVSqAhxJYmMuQXBwbGljYXRpb25zLlRyYW5zZmVyLlYxygIcSWJjXEFwcGxpY2F0aW9uc1xUcmFuc2ZlclxWMeICKEliY1xBcHBsaWNhdGlvbnNcVHJhbnNmZXJcVjFcR1BCTWV0YWRhdGHqAh9JYmM6OkFwcGxpY2F0aW9uczo6VHJhbnNmZXI6OlYxYgZwcm90bzM", [file_ibc_applications_transfer_v1_transfer, file_ibc_applications_transfer_v1_token, file_cosmos_base_v1beta1_coin, file_gogoproto_gogo]);

/**
 * GenesisState defines the ibc-transfer genesis state
 *
 * @generated from message ibc.applications.transfer.v1.GenesisState
 */
export type GenesisState = Message<"ibc.applications.transfer.v1.GenesisState"> & {
  /**
   * @generated from field: string port_id = 1;
   */
  portId: string;

  /**
   * @generated from field: repeated ibc.applications.transfer.v1.Denom denoms = 2;
   */
  denoms: Denom[];

  /**
   * @generated from field: ibc.applications.transfer.v1.Params params = 3;
   */
  params?: Params;

  /**
   * total_escrowed contains the total amount of tokens escrowed
   * by the transfer module
   *
   * @generated from field: repeated cosmos.base.v1beta1.Coin total_escrowed = 4;
   */
  totalEscrowed: Coin[];
};

/**
 * Describes the message ibc.applications.transfer.v1.GenesisState.
 * Use `create(GenesisStateSchema)` to create a new message.
 */
export const GenesisStateSchema: GenMessage<GenesisState> = /*@__PURE__*/
  messageDesc(file_ibc_applications_transfer_v1_genesis, 0);

