// Since: cosmos-sdk 0.46

// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file dysonprotocol/script/v1/events.proto (package dysonprotocol.script.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64 } from "@bufbuild/protobuf";
import { MsgExec, MsgExecResponse } from "./tx_pb.js";

/**
 * EventUpdateScript is an event emitted when a script is updated.
 *
 * @generated from message dysonprotocol.script.v1.EventUpdateScript
 */
export class EventUpdateScript extends Message<EventUpdateScript> {
  /**
   * The new version of the script.
   *
   * @generated from field: uint64 version = 1;
   */
  version = protoInt64.zero;

  /**
   * The address of the script.
   *
   * @generated from field: string script_address = 2;
   */
  scriptAddress = "";

  constructor(data?: PartialMessage<EventUpdateScript>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dysonprotocol.script.v1.EventUpdateScript";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "version", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 2, name: "script_address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): EventUpdateScript {
    return new EventUpdateScript().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): EventUpdateScript {
    return new EventUpdateScript().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): EventUpdateScript {
    return new EventUpdateScript().fromJsonString(jsonString, options);
  }

  static equals(a: EventUpdateScript | PlainMessage<EventUpdateScript> | undefined, b: EventUpdateScript | PlainMessage<EventUpdateScript> | undefined): boolean {
    return proto3.util.equals(EventUpdateScript, a, b);
  }
}

/**
 * Event ExecScript is an event emitted when a script is executed.
 *
 * @generated from message dysonprotocol.script.v1.EventExecScript
 */
export class EventExecScript extends Message<EventExecScript> {
  /**
   * The result of the script execution.
   *
   * @generated from field: dysonprotocol.script.v1.MsgExec request = 1;
   */
  request?: MsgExec;

  /**
   * @generated from field: dysonprotocol.script.v1.MsgExecResponse response = 2;
   */
  response?: MsgExecResponse;

  /**
   * Executor and target identifiers for indexing
   *
   * @generated from field: string executor_address = 3;
   */
  executorAddress = "";

  /**
   * @generated from field: string script_address = 4;
   */
  scriptAddress = "";

  /**
   * @generated from field: string script_name = 5;
   */
  scriptName = "";

  /**
   * @generated from field: string function_name = 6;
   */
  functionName = "";

  constructor(data?: PartialMessage<EventExecScript>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dysonprotocol.script.v1.EventExecScript";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "request", kind: "message", T: MsgExec },
    { no: 2, name: "response", kind: "message", T: MsgExecResponse },
    { no: 3, name: "executor_address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "script_address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "script_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "function_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): EventExecScript {
    return new EventExecScript().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): EventExecScript {
    return new EventExecScript().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): EventExecScript {
    return new EventExecScript().fromJsonString(jsonString, options);
  }

  static equals(a: EventExecScript | PlainMessage<EventExecScript> | undefined, b: EventExecScript | PlainMessage<EventExecScript> | undefined): boolean {
    return proto3.util.equals(EventExecScript, a, b);
  }
}

/**
 * EventScriptEvent is an event emitted by the script itself.
 *
 * @generated from message dysonprotocol.script.v1.EventScriptEvent
 */
export class EventScriptEvent extends Message<EventScriptEvent> {
  /**
   * Address of the script
   *
   * @generated from field: string address = 1;
   */
  address = "";

  /**
   * The key of the event.
   *
   * @generated from field: string key = 2;
   */
  key = "";

  /**
   * The value of the event.
   *
   * @generated from field: string value = 3;
   */
  value = "";

  constructor(data?: PartialMessage<EventScriptEvent>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dysonprotocol.script.v1.EventScriptEvent";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "key", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): EventScriptEvent {
    return new EventScriptEvent().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): EventScriptEvent {
    return new EventScriptEvent().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): EventScriptEvent {
    return new EventScriptEvent().fromJsonString(jsonString, options);
  }

  static equals(a: EventScriptEvent | PlainMessage<EventScriptEvent> | undefined, b: EventScriptEvent | PlainMessage<EventScriptEvent> | undefined): boolean {
    return proto3.util.equals(EventScriptEvent, a, b);
  }
}

/**
 * EventCreateNewScript is an event emitted when a new script is created.
 *
 * @generated from message dysonprotocol.script.v1.EventCreateNewScript
 */
export class EventCreateNewScript extends Message<EventCreateNewScript> {
  /**
   * The address of the newly created script.
   *
   * @generated from field: string script_address = 1;
   */
  scriptAddress = "";

  /**
   * The address of the creator.
   *
   * @generated from field: string creator_address = 2;
   */
  creatorAddress = "";

  /**
   * The initial version of the script.
   *
   * @generated from field: uint64 version = 3;
   */
  version = protoInt64.zero;

  constructor(data?: PartialMessage<EventCreateNewScript>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dysonprotocol.script.v1.EventCreateNewScript";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "script_address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "creator_address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "version", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): EventCreateNewScript {
    return new EventCreateNewScript().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): EventCreateNewScript {
    return new EventCreateNewScript().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): EventCreateNewScript {
    return new EventCreateNewScript().fromJsonString(jsonString, options);
  }

  static equals(a: EventCreateNewScript | PlainMessage<EventCreateNewScript> | undefined, b: EventCreateNewScript | PlainMessage<EventCreateNewScript> | undefined): boolean {
    return proto3.util.equals(EventCreateNewScript, a, b);
  }
}

