// Since: cosmos-sdk 0.46

// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file dysonprotocol/script/v1/tx.proto (package dysonprotocol.script.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Any, Message, proto3, protoInt64 } from "@bufbuild/protobuf";
import { Params } from "./params_pb.js";

/**
 *
 * MsgUpdateScript updates the script code at the given address and increments
 * its version.
 *
 * Behavior:
 * - Updates or creates a script at the specified address with formatted code.
 * - Automatically formats the provided code using DysFormat before storage.
 * - Increments the script version on each update.
 * - Sets update metadata including block height.
 * - Creates new scripts with empty code if they don't exist.
 *
 * Validation:
 * - Address must be a valid bech32 address.
 * - Code must be valid Python syntax that can be formatted by DysFormat.
 *
 * Emits:
 * - EventUpdateScript(version, script_address) on successful update.
 *
 * Returns:
 * - updated script version.
 *
 * @generated from message dysonprotocol.script.v1.MsgUpdateScript
 */
export class MsgUpdateScript extends Message<MsgUpdateScript> {
  /**
   * Account address of the script to update; must be a valid bech32 address.
   *
   * @generated from field: string address = 1;
   */
  address = "";

  /**
   * Python script code to store; will be automatically formatted before
   * storage.
   *
   * @generated from field: string code = 2;
   */
  code = "";

  constructor(data?: PartialMessage<MsgUpdateScript>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dysonprotocol.script.v1.MsgUpdateScript";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "code", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgUpdateScript {
    return new MsgUpdateScript().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgUpdateScript {
    return new MsgUpdateScript().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgUpdateScript {
    return new MsgUpdateScript().fromJsonString(jsonString, options);
  }

  static equals(a: MsgUpdateScript | PlainMessage<MsgUpdateScript> | undefined, b: MsgUpdateScript | PlainMessage<MsgUpdateScript> | undefined): boolean {
    return proto3.util.equals(MsgUpdateScript, a, b);
  }
}

/**
 *
 * Empty response. See EventUpdateScript for emitted details.
 *
 * @generated from message dysonprotocol.script.v1.MsgUpdateScriptResponse
 */
export class MsgUpdateScriptResponse extends Message<MsgUpdateScriptResponse> {
  /**
   * Updated script version after the update operation.
   *
   * @generated from field: uint64 version = 1;
   */
  version = protoInt64.zero;

  constructor(data?: PartialMessage<MsgUpdateScriptResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dysonprotocol.script.v1.MsgUpdateScriptResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "version", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgUpdateScriptResponse {
    return new MsgUpdateScriptResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgUpdateScriptResponse {
    return new MsgUpdateScriptResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgUpdateScriptResponse {
    return new MsgUpdateScriptResponse().fromJsonString(jsonString, options);
  }

  static equals(a: MsgUpdateScriptResponse | PlainMessage<MsgUpdateScriptResponse> | undefined, b: MsgUpdateScriptResponse | PlainMessage<MsgUpdateScriptResponse> | undefined): boolean {
    return proto3.util.equals(MsgUpdateScriptResponse, a, b);
  }
}

/**
 *
 * MsgExec executes a script function with arguments and handles attached
 * messages.
 *
 * Behavior:
 * - Resolves script address via direct address or nameservice name resolution.
 * - Validates that script exists or creates empty script if not found.
 * - Executes attached messages first, collecting their results.
 * - Runs the specified function with provided args/kwargs in isolated context.
 * - Commits state changes only if execution succeeds.
 * - Emits execution event with full context for monitoring.
 *
 * Validation:
 * - Either script_address or script_name must be provided.
 * - If both are provided, they must resolve to the same address.
 * - Executor address must be valid.
 * - Function name, args, kwargs must be valid JSON strings.
 * - Attached messages must be valid and executable.
 *
 * Emits:
 * - EventExecScript with execution details (executor, script, function,
 * result).
 *
 * Returns:
 * - function execution result and attached message results.
 *
 * @generated from message dysonprotocol.script.v1.MsgExec
 */
export class MsgExec extends Message<MsgExec> {
  /**
   * Account address used to execute the script; must be a valid bech32 address.
   *
   * @generated from field: string executor_address = 1;
   */
  executorAddress = "";

  /**
   * Script bech32 address to execute; mutually exclusive with script_name.
   *
   * @generated from field: string script_address = 2;
   */
  scriptAddress = "";

  /**
   * Optional nameservice name of the script to execute (e.g., "example.dys").
   *
   * @generated from field: string script_name = 3;
   */
  scriptName = "";

  /**
   * Optional extra code temporarily appended to the script for this execution.
   * Only allowed if the executor is the script owner.
   *
   * @generated from field: string extra_code = 4;
   */
  extraCode = "";

  /**
   * Name of the function to call within the script.
   *
   * @generated from field: string function_name = 5;
   */
  functionName = "";

  /**
   * Positional arguments (*args) encoded as a JSON array.
   *
   * @generated from field: string args = 6;
   */
  args = "";

  /**
   * Keyword arguments (**kwargs) encoded as a JSON object.
   *
   * @generated from field: string kwargs = 7;
   */
  kwargs = "";

  /**
   * Messages executed before the script; results available via
   * dys.get_attached_messages(). If any attached message fails, script
   * execution is aborted. Messages execute in order.
   *
   * @generated from field: repeated google.protobuf.Any attached_messages = 8;
   */
  attachedMessages: Any[] = [];

  constructor(data?: PartialMessage<MsgExec>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dysonprotocol.script.v1.MsgExec";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "executor_address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "script_address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "script_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "extra_code", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "function_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "args", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "kwargs", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "attached_messages", kind: "message", T: Any, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgExec {
    return new MsgExec().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgExec {
    return new MsgExec().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgExec {
    return new MsgExec().fromJsonString(jsonString, options);
  }

  static equals(a: MsgExec | PlainMessage<MsgExec> | undefined, b: MsgExec | PlainMessage<MsgExec> | undefined): boolean {
    return proto3.util.equals(MsgExec, a, b);
  }
}

/**
 *
 * Response containing script execution results and attached message outcomes.
 *
 * @generated from message dysonprotocol.script.v1.MsgExecResponse
 */
export class MsgExecResponse extends Message<MsgExecResponse> {
  /**
   * Final result of the script function execution.
   *
   * @generated from field: string result = 1;
   */
  result = "";

  /**
   * Results of the attached messages executed before the script.
   *
   * @generated from field: repeated google.protobuf.Any attached_message_results = 2;
   */
  attachedMessageResults: Any[] = [];

  constructor(data?: PartialMessage<MsgExecResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dysonprotocol.script.v1.MsgExecResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "result", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "attached_message_results", kind: "message", T: Any, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgExecResponse {
    return new MsgExecResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgExecResponse {
    return new MsgExecResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgExecResponse {
    return new MsgExecResponse().fromJsonString(jsonString, options);
  }

  static equals(a: MsgExecResponse | PlainMessage<MsgExecResponse> | undefined, b: MsgExecResponse | PlainMessage<MsgExecResponse> | undefined): boolean {
    return proto3.util.equals(MsgExecResponse, a, b);
  }
}

/**
 *
 * MsgCreateNewScript creates a new script with deterministic address and grants
 * update permissions.
 *
 * Behavior:
 * - Generates deterministic script address using SHA256 hash of creator +
 * formatted code.
 * - Creates bech32 address from first 20 bytes of hash.
 * - Formats code using DysFormat before address generation and storage.
 * - Grants generic authorization for MsgUpdateScript to creator via authz.
 * - Initializes script with version 1 and formatted code.
 *
 * Validation:
 * - Creator address must be valid.
 * - Code must be valid Python syntax that can be formatted by DysFormat.
 * - Generated address must not already exist.
 *
 * Emits:
 * - EventCreateNewScript(script_address, creator_address, version) on success.
 *
 * Returns:
 * - generated script address and initial version.
 *
 * @generated from message dysonprotocol.script.v1.MsgCreateNewScript
 */
export class MsgCreateNewScript extends Message<MsgCreateNewScript> {
  /**
   * Account address creating the script; must be a valid bech32 address.
   *
   * @generated from field: string creator_address = 1;
   */
  creatorAddress = "";

  /**
   * Python script content; will be formatted and used to generate deterministic
   * address.
   *
   * @generated from field: string code = 2;
   */
  code = "";

  constructor(data?: PartialMessage<MsgCreateNewScript>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dysonprotocol.script.v1.MsgCreateNewScript";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "creator_address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "code", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgCreateNewScript {
    return new MsgCreateNewScript().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgCreateNewScript {
    return new MsgCreateNewScript().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgCreateNewScript {
    return new MsgCreateNewScript().fromJsonString(jsonString, options);
  }

  static equals(a: MsgCreateNewScript | PlainMessage<MsgCreateNewScript> | undefined, b: MsgCreateNewScript | PlainMessage<MsgCreateNewScript> | undefined): boolean {
    return proto3.util.equals(MsgCreateNewScript, a, b);
  }
}

/**
 *
 * Response containing the newly created script details.
 *
 * @generated from message dysonprotocol.script.v1.MsgCreateNewScriptResponse
 */
export class MsgCreateNewScriptResponse extends Message<MsgCreateNewScriptResponse> {
  /**
   * Address of the newly created script, generated deterministically.
   *
   * @generated from field: string script_address = 1;
   */
  scriptAddress = "";

  /**
   * Initial script version (always 1 for new scripts).
   *
   * @generated from field: uint64 version = 2;
   */
  version = protoInt64.zero;

  constructor(data?: PartialMessage<MsgCreateNewScriptResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dysonprotocol.script.v1.MsgCreateNewScriptResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "script_address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "version", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgCreateNewScriptResponse {
    return new MsgCreateNewScriptResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgCreateNewScriptResponse {
    return new MsgCreateNewScriptResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgCreateNewScriptResponse {
    return new MsgCreateNewScriptResponse().fromJsonString(jsonString, options);
  }

  static equals(a: MsgCreateNewScriptResponse | PlainMessage<MsgCreateNewScriptResponse> | undefined, b: MsgCreateNewScriptResponse | PlainMessage<MsgCreateNewScriptResponse> | undefined): boolean {
    return proto3.util.equals(MsgCreateNewScriptResponse, a, b);
  }
}

/**
 *
 * MsgUpdateParams updates the module parameters via governance proposal.
 *
 * Behavior:
 * - Validates that the signer has authority to update parameters (gov module).
 * - Validates that all provided parameters are valid.
 * - Updates all module parameters atomically.
 *
 * Validation:
 * - Authority must match the configured authority (gov module account).
 * - All parameters in the params message must pass individual validation.
 *
 * Returns:
 * - empty response on successful parameter update.
 *
 * @generated from message dysonprotocol.script.v1.MsgUpdateParams
 */
export class MsgUpdateParams extends Message<MsgUpdateParams> {
  /**
   * Address that controls the module (defaults to x/gov unless overwritten).
   *
   * @generated from field: string authority = 1;
   */
  authority = "";

  /**
   * Script module parameters to update; all parameters must be supplied.
   *
   * @generated from field: dysonprotocol.script.v1.Params params = 2;
   */
  params?: Params;

  constructor(data?: PartialMessage<MsgUpdateParams>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dysonprotocol.script.v1.MsgUpdateParams";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "authority", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "params", kind: "message", T: Params },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgUpdateParams {
    return new MsgUpdateParams().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgUpdateParams {
    return new MsgUpdateParams().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgUpdateParams {
    return new MsgUpdateParams().fromJsonString(jsonString, options);
  }

  static equals(a: MsgUpdateParams | PlainMessage<MsgUpdateParams> | undefined, b: MsgUpdateParams | PlainMessage<MsgUpdateParams> | undefined): boolean {
    return proto3.util.equals(MsgUpdateParams, a, b);
  }
}

/**
 *
 * Empty response indicating successful parameter update.
 *
 * @generated from message dysonprotocol.script.v1.MsgUpdateParamsResponse
 */
export class MsgUpdateParamsResponse extends Message<MsgUpdateParamsResponse> {
  constructor(data?: PartialMessage<MsgUpdateParamsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dysonprotocol.script.v1.MsgUpdateParamsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgUpdateParamsResponse {
    return new MsgUpdateParamsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgUpdateParamsResponse {
    return new MsgUpdateParamsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgUpdateParamsResponse {
    return new MsgUpdateParamsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: MsgUpdateParamsResponse | PlainMessage<MsgUpdateParamsResponse> | undefined, b: MsgUpdateParamsResponse | PlainMessage<MsgUpdateParamsResponse> | undefined): boolean {
    return proto3.util.equals(MsgUpdateParamsResponse, a, b);
  }
}

/**
 * MsgArbitraryData is used for signing arbitrary data for verification purposes
 *
 * @generated from message dysonprotocol.script.v1.MsgArbitraryData
 */
export class MsgArbitraryData extends Message<MsgArbitraryData> {
  /**
   * signer is the account address signing the data
   *
   * @generated from field: string signer = 1;
   */
  signer = "";

  /**
   * data is the arbitrary data being signed
   *
   * @generated from field: string data = 2;
   */
  data = "";

  /**
   * app_domain is an optional application domain for the data
   *
   * @generated from field: string app_domain = 3;
   */
  appDomain = "";

  constructor(data?: PartialMessage<MsgArbitraryData>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dysonprotocol.script.v1.MsgArbitraryData";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "signer", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "data", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "app_domain", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgArbitraryData {
    return new MsgArbitraryData().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgArbitraryData {
    return new MsgArbitraryData().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgArbitraryData {
    return new MsgArbitraryData().fromJsonString(jsonString, options);
  }

  static equals(a: MsgArbitraryData | PlainMessage<MsgArbitraryData> | undefined, b: MsgArbitraryData | PlainMessage<MsgArbitraryData> | undefined): boolean {
    return proto3.util.equals(MsgArbitraryData, a, b);
  }
}

/**
 * MsgArbitraryDataResponse is the response for MsgArbitraryData
 *
 * @generated from message dysonprotocol.script.v1.MsgArbitraryDataResponse
 */
export class MsgArbitraryDataResponse extends Message<MsgArbitraryDataResponse> {
  constructor(data?: PartialMessage<MsgArbitraryDataResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dysonprotocol.script.v1.MsgArbitraryDataResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgArbitraryDataResponse {
    return new MsgArbitraryDataResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgArbitraryDataResponse {
    return new MsgArbitraryDataResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgArbitraryDataResponse {
    return new MsgArbitraryDataResponse().fromJsonString(jsonString, options);
  }

  static equals(a: MsgArbitraryDataResponse | PlainMessage<MsgArbitraryDataResponse> | undefined, b: MsgArbitraryDataResponse | PlainMessage<MsgArbitraryDataResponse> | undefined): boolean {
    return proto3.util.equals(MsgArbitraryDataResponse, a, b);
  }
}

/**
 *
 * MsgSudo executes arbitrary messages with authority override and no signer
 * validation.
 *
 * Behavior:
 * - Validates that the signer has governance authority.
 * - Unpacks and executes all provided messages atomically using cached context.
 * - Messages execute without signer validation (authority override).
 * - If any message fails, all state changes are discarded.
 *
 * Validation:
 * - Authority must match the configured authority (gov module account).
 * - All messages must be valid and unpackable.
 *
 * Returns:
 * - results from all executed messages.
 *
 * @generated from message dysonprotocol.script.v1.MsgSudo
 */
export class MsgSudo extends Message<MsgSudo> {
  /**
   * Address that controls the module (defaults to x/gov unless overwritten).
   *
   * @generated from field: string authority = 1;
   */
  authority = "";

  /**
   * Messages to execute without signer validation; executed atomically in
   * order.
   *
   * @generated from field: repeated google.protobuf.Any messages = 2;
   */
  messages: Any[] = [];

  constructor(data?: PartialMessage<MsgSudo>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dysonprotocol.script.v1.MsgSudo";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "authority", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "messages", kind: "message", T: Any, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgSudo {
    return new MsgSudo().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgSudo {
    return new MsgSudo().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgSudo {
    return new MsgSudo().fromJsonString(jsonString, options);
  }

  static equals(a: MsgSudo | PlainMessage<MsgSudo> | undefined, b: MsgSudo | PlainMessage<MsgSudo> | undefined): boolean {
    return proto3.util.equals(MsgSudo, a, b);
  }
}

/**
 *
 * Response containing results from all executed sudo messages.
 *
 * @generated from message dysonprotocol.script.v1.MsgSudoResponse
 */
export class MsgSudoResponse extends Message<MsgSudoResponse> {
  /**
   * Response messages from each executed sudo message.
   *
   * @generated from field: repeated google.protobuf.Any results = 1;
   */
  results: Any[] = [];

  constructor(data?: PartialMessage<MsgSudoResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "dysonprotocol.script.v1.MsgSudoResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "results", kind: "message", T: Any, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgSudoResponse {
    return new MsgSudoResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgSudoResponse {
    return new MsgSudoResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgSudoResponse {
    return new MsgSudoResponse().fromJsonString(jsonString, options);
  }

  static equals(a: MsgSudoResponse | PlainMessage<MsgSudoResponse> | undefined, b: MsgSudoResponse | PlainMessage<MsgSudoResponse> | undefined): boolean {
    return proto3.util.equals(MsgSudoResponse, a, b);
  }
}

