// @generated by protoc-gen-es v2.9.0 with parameter "target=ts"
// @generated from file dysonprotocol/crontask/module/v1/module.proto (package dysonprotocol.crontask.module.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_cosmos_app_v1alpha1_module } from "../../../../cosmos/app/v1alpha1/module_pb";
import { file_gogoproto_gogo } from "../../../../gogoproto/gogo_pb";
import type { Duration } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_duration } from "@bufbuild/protobuf/wkt";
import { file_amino_amino } from "../../../../amino/amino_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file dysonprotocol/crontask/module/v1/module.proto.
 */
export const file_dysonprotocol_crontask_module_v1_module: GenFile = /*@__PURE__*/
  fileDesc("Ci1keXNvbnByb3RvY29sL2Nyb250YXNrL21vZHVsZS92MS9tb2R1bGUucHJvdG8SIGR5c29ucHJvdG9jb2wuY3JvbnRhc2subW9kdWxlLnYxIpABCgZNb2R1bGUSRgoUbWF4X2V4ZWN1dGlvbl9wZXJpb2QYASABKAsyGS5nb29nbGUucHJvdG9idWYuRHVyYXRpb25CDcjeHwCY3x8BqOewKgESGAoQbWF4X21ldGFkYXRhX2xlbhgCIAEoBDokusCW2gEeChxkeXNvbnByb3RvY29sLmNvbS94L2Nyb250YXNrQv4BCiRjb20uZHlzb25wcm90b2NvbC5jcm9udGFzay5tb2R1bGUudjFCC01vZHVsZVByb3RvUAFaJmR5c29ucHJvdG9jb2wuY29tL3gvY3JvbnRhc2svbW9kdWxlL3YxogIDRENNqgIgRHlzb25wcm90b2NvbC5Dcm9udGFzay5Nb2R1bGUuVjHKAiBEeXNvbnByb3RvY29sXENyb250YXNrXE1vZHVsZVxWMeICLER5c29ucHJvdG9jb2xcQ3JvbnRhc2tcTW9kdWxlXFYxXEdQQk1ldGFkYXRh6gIjRHlzb25wcm90b2NvbDo6Q3JvbnRhc2s6Ok1vZHVsZTo6VjFiBnByb3RvMw", [file_cosmos_app_v1alpha1_module, file_gogoproto_gogo, file_google_protobuf_duration, file_amino_amino]);

/**
 * Module is the config object of the crontask module.
 *
 * @generated from message dysonprotocol.crontask.module.v1.Module
 */
export type Module = Message<"dysonprotocol.crontask.module.v1.Module"> & {
  /**
   * max_execution_period defines the max duration after a cron task is
   * scheduled that it can be executed.
   *
   * @generated from field: google.protobuf.Duration max_execution_period = 1;
   */
  maxExecutionPeriod?: Duration;

  /**
   * MaxMetadataLen defines the max chars allowed in metadata field
   * Defaults to 255 if not explicitly set.
   *
   * @generated from field: uint64 max_metadata_len = 2;
   */
  maxMetadataLen: bigint;
};

/**
 * Describes the message dysonprotocol.crontask.module.v1.Module.
 * Use `create(ModuleSchema)` to create a new message.
 */
export const ModuleSchema: GenMessage<Module> = /*@__PURE__*/
  messageDesc(file_dysonprotocol_crontask_module_v1_module, 0);

